function JX(){}
function Oyb(){}
function SU(a,b){a.f=b}
function Vd(a,b){a.Cc(b)}
function ae(a,b){a.Cc(b)}
function bc(a){this.a=a}
function xyb(a){this.Bc=a}
function Db(a){lb(a,a.a)}
function Pd(){return new Ag}
function xg(a,b){vb.call(this,a,b)}
function azb(a){MA.call(this);this.a=a}
function Mzb(a){this.c=a;this.a=!!this.c.r}
function LX(){kK.call(this);this.t=G9b;this.u=true}
function ac(a){!!a.a.k&&Db(vbb(a.a.k,10))}
function uyb(a,b){if(a.r){throw new mGb(L9b)}wyb(a,b)}
function Lzb(a){if(!a.a||!a.c.r){throw new pNb}a.a=false;return a.b=a.c.r}
function Eb(a,b,c){Cb();vb.call(this,a,b);this.a=c;vbb(this.g,2).Kc(this)}
function vyb(a,b){if(a.r!=b){return false}try{ji(b,null)}finally{E3(a._g(),b.Zc());a.r=null}return true}
function wyb(a,b){if(b==a.r){return}!!b&&(xbb(b.Ac,57)&&vbb(b.Ac,57).wf(b),hi(b));!!a.r&&vyb(a,a.r);a.r=b;if(b){wsb(T3(a.Bc),Ki(a.r));ji(b,a)}}
function Iyb(){xyb.call(this,W3($doc,xPb));this.d=new Oyb;this.o=new azb(this);B3(this.Bc,W3($doc,xPb));Fyb(this,0,0);U3(T3(this.Bc))[NQb]=M9b;T3(this.Bc)[NQb]=N9b}
function $yb(a,b){var c,d,e,g,i,j;a.i||(b=1-b);i=0;e=0;g=0;c=0;d=Bbb(b*a.d);j=Bbb(b*a.e);switch(0){case 2:case 0:i=a.d-d>>1;e=a.e-j>>1;g=e+j;c=i+d;}CAb(a.a.Bc,O9b+i+P9b+g+P9b+c+P9b+e+Q9b)}
function he(a){var b,c;!a.b&&(a.b=(b=new Eb((!a.B&&(a.B=new y7),a.B),(!a.c&&(a.c=new Vb(new Rg)),a.c),(!a.a&&(a.a=new Ob),c=new xg((!a.B&&(a.B=new y7),a.B),Pd(!a.B&&(a.B=new y7))),ae(c,(!a.E&&(a.E=new cCb),a.E)),c)),Vd(b,(!a.E&&(a.E=new cCb),a.E)),b));return a.b}
function Ag(){var a,b,c,d;this.b=new Iyb;new XKb;this.b.j=true;this.b.b=true;this.b.a=true;this.b.f=true;this.a=new VU;kk(this.a,800,-1);SU(this.a,(jV(),iV));fH(this.a,(ln(),hn));d=new JG(new LX);a=vbb(d.lb,87);a.a=true;d.Mb=1;d.jc&&js(Us(Ki(d),N2b),true);c=new IG;b=new kY;jY(b,iV);_F(c,b);uyb(this.b,this.a)}
function Vb(){var a,b,c,d,e,g;this.b=new JG(new dX);dj(this.b,true);kj(this.b,Jbb.d);d=new iH;d.Ff(E9b);a=new GX((En(),Dn));a.a=true;a.f=true;g=new kQ;g.Mb=1;g.jc&&js(Us(Ki(g),N2b),true);g.sb=true;g.rb=true;b=new JP(F9b,Axb((Sg(),Qg(),Gg)));uP(b,new bc(this));gQ(g,b,g.kb.b);e=new C0;e.Mb=1;e.jc&&js(Us(Ki(e),N2b),true);gQ(g,e,g.kb.b);c=new JP(X6b,Axb((Ug(),Ig)));gQ(g,c,g.kb.b);CG(d,g,d.kb.b);this.a=new IG;_F(this.a,new ZX);dj(this.a,true);AG(this.b,d,a);_F(d,new TX(0));vG(d,(On(),Kn));AG(this.b,this.a,new GX(zn))}
var J9b="<div class='x-clear'><\/div>",I9b="<div class='x-column-inner'><\/div>",F9b='Add',cac='ColumnData',Y9b='ColumnLayout',S9b='HomePresenter',T9b='HomeView$1',$9b='PopupPanel',aac='PopupPanel$1',_9b='PopupPanel$ResizeAnimation',E9b='Projects',Z9b='SimplePanel',L9b='SimplePanel can only contain one child widget',bac='SimplePanel$1',V9b='TeamEditorPresenter',W9b='TeamEditorView',U9b='co.edu.unal.scrum.client.projects.',M9b='gwt-PopupPanel',N9b='popupContent',Q9b='px)',P9b='px, ',O9b='rect(',H9b='x-column-layout-ct';eqb(5,6,{10:1,117:1,157:1},Eb);_.Dc=function Fb(){};_.Fc=function Gb(){};_.Gc=function Hb(){};_.Hc=function Ib(){ob(this,new BEb((Lc(),Fc),this))};_.a=null;eqb(11,12,{2:1},Vb);_.Lc=function Wb(){return this.b};_.Jc=function Xb(a,b){if(a===(Cb(),Ab)){if(b){$F(this.a);zG(this.a,b)}}};_.a=null;_.b=null;eqb(14,15,UNb,bc);_.Mc=function cc(a){ac(this,vbb(a,30))};_.a=null;eqb(45,1,YNb);_.Xc=function We(){lDb(this.b,he(this.a.a))};eqb(65,7,RNb,xg);_.Dc=function yg(){};eqb(66,28,XNb,Ag);_.Lc=function Bg(){return this.b};_.a=null;_.b=null;eqb(385,376,{86:1,89:1},JX);eqb(386,281,{87:1},LX);_.Nf=function MX(a,b){var c,d,e,g,i,j,k;if(!this.b){xi(a,H9b);this.b=dr(b,ov(I9b));dr(this.b,ov(J9b))}fK(this,a,this.b);j=Gr(b,true);k=j.b-(this.a?(nv(),lv==-1&&(lv=tv()),nv(),lv):0);i=k;d=a.kb.b;for(g=0;g<d;++g){c=g<a.kb.b?vbb(PKb(a.kb,g),55):null;e=vbb(Ji(c,K9b),89);!!e&&xbb(e,86)?vbb(e,86):new JX;i-=ZJ(c)}for(g=0;g<d;++g){c=g<a.kb.b?vbb(PKb(a.kb,g),55):null;e=vbb(Ji(c,K9b),89);!!e&&xbb(e,86)?vbb(e,86):new JX;xbb(c,53)?kk(vbb(c,53),-1,-1):c.jc&&ws(YJ(c.Zc()),-1,-1,true)}};_.a=false;_.b=null;eqb(686,672,VOb);_._g=function yyb(){return this.Bc};_.ze=function zyb(){return new Mzb(this)};_.Yg=function Ayb(a){return vyb(this,a)};_.r=null;eqb(685,686,{113:1,117:1,135:1,142:1,143:1,144:1,145:1,146:1,149:1,150:1},Iyb);_._g=function Jyb(){return T3(this.Bc)};_.$c=function Kyb(){return !BHb(HQb,this.Bc.style[GQb])};_.gd=function Lyb(){this.p&&_yb(this.o,false,true)};_.a=false;_.b=false;_.c=null;_.e=null;_.f=false;_.g=false;_.i=-1;_.j=false;_.k=null;_.n=false;_.p=false;_.q=-1;eqb(687,1,yOb,Oyb);_.If=function Pyb(a){Nyb()};eqb(690,212,{},azb);_.Qe=function bzb(){Yyb(this)};_.Re=function czb(){this.d=I3(this.a.Bc,R9b);this.e=I3(this.a.Bc,j4b);this.a.Bc.style[B7b]=HQb;$yb(this,(1+Math.cos(3.141592653589793))/2)};_.Se=function dzb(a){$yb(this,a)};_.a=null;_.b=false;_.c=false;_.d=0;_.e=-1;_.f=null;_.g=null;_.i=false;eqb(699,1,{},Mzb);_.De=function Nzb(){return this.a};_.Ee=function Ozb(){return Lzb(this)};_.Fe=function Pzb(){!!this.b&&vyb(this.c,this.b)};_.b=null;_.c=null;var Hbb=zFb(BYb,S9b,5),Ibb=zFb(BYb,T9b,14),Acb=zFb(U9b,V9b,65),Bcb=zFb(U9b,W9b,66),Ihb=zFb(X9b,Y9b,386),Tlb=zFb(m1b,Z9b,686),Llb=zFb(m1b,$9b,685),Klb=zFb(m1b,_9b,690),Glb=zFb(m1b,aac,687),Slb=zFb(m1b,bac,699),Hhb=zFb(X9b,cac,385);gPb(X1)(5);