function EX(){}
function Nxb(){}
function NU(a,b){a.f=b}
function Ud(a,b){a.Cc(b)}
function _d(a,b){a.Cc(b)}
function ac(a){this.a=a}
function wxb(a){this.Bc=a}
function Cb(a){kb(a,a.a)}
function Od(){return new zg}
function wg(a,b){ub.call(this,a,b)}
function _xb(a){HA.call(this);this.a=a}
function Lyb(a){this.c=a;this.a=!!this.c.r}
function GX(){fK.call(this);this.t=xTb;this.u=true}
function _b(a){!!a.a.k&&Cb(gbb(a.a.k,10))}
function Kyb(a){if(!a.a||!a.c.r){throw new bMb}a.a=false;return a.b=a.c.r}
function Db(a,b,c){Bb();ub.call(this,a,b);this.a=c;gbb(this.g,2).Kc(this)}
function txb(a,b){if(a.r){throw new _Eb('SimplePanel can only contain one child widget')}vxb(a,b)}
function uxb(a,b){if(a.r!=b){return false}try{gi(b,null)}finally{z3(a.Zg(),b.Zc());a.r=null}return true}
function vxb(a,b){if(b==a.r){return}!!b&&(ibb(b.Ac,57)&&gbb(b.Ac,57).vf(b),ei(b));!!a.r&&uxb(a,a.r);a.r=b;if(b){Erb(O3(a.Bc),Hi(a.r));gi(b,a)}}
function Zxb(a,b){var c,d,e,g,i,j;a.i||(b=1-b);i=0;e=0;g=0;c=0;d=mbb(b*a.d);j=mbb(b*a.e);switch(0){case 2:case 0:i=a.d-d>>1;e=a.e-j>>1;g=e+j;c=i+d;}szb(a.a.Bc,'rect('+i+zTb+g+zTb+c+zTb+e+'px)')}
function Hxb(){wxb.call(this,$doc.createElement(dOb));this.d=new Nxb;this.o=new _xb(this);w3(this.Bc,$doc.createElement(dOb));Exb(this,0,0);P3(O3(this.Bc))[GOb]='gwt-PopupPanel';O3(this.Bc)[GOb]='popupContent'}
function ge(a){var b,c;!a.b&&(a.b=(b=new Db((!a.B&&(a.B=new $6),a.B),(!a.c&&(a.c=new Ub(new Og)),a.c),(!a.a&&(a.a=new Nb),c=new wg((!a.B&&(a.B=new $6),a.B),Od(!a.B&&(a.B=new $6))),_d(c,(!a.E&&(a.E=new RAb),a.E)),c)),Ud(b,(!a.E&&(a.E=new RAb),a.E)),b));return a.b}
function zg(){var a,b,c,d;this.b=new Hxb;new JJb;this.b.j=true;this.b.b=true;this.b.a=true;this.b.f=true;this.a=new QU;hk(this.a,800,-1);NU(this.a,(eV(),dV));aH(this.a,(gn(),dn));d=new EG(new GX);a=gbb(d.lb,87);a.a=true;d.Mb=1;d.jc&&fs(Qs(Hi(d),BRb),true);c=new DG;b=new fY;eY(b,dV);WF(c,b);txb(this.b,this.a)}
function Ub(){var a,b,c,d,e,g;this.b=new EG(new $W);aj(this.b,true);hj(this.b,ubb.d);d=new dH;d.Ef('Projects');a=new BX((An(),zn));a.a=true;a.f=true;g=new fQ;g.Mb=1;g.jc&&fs(Qs(Hi(g),BRb),true);g.sb=true;g.rb=true;b=new EP('Add',zwb((Pg(),Ng(),Dg)));pP(b,new ac(this));bQ(g,b,g.kb.b);e=new x0;e.Mb=1;e.jc&&fs(Qs(Hi(e),BRb),true);bQ(g,e,g.kb.b);c=new EP(PSb,zwb((Rg(),Fg)));bQ(g,c,g.kb.b);xG(d,g,d.kb.b);this.a=new DG;WF(this.a,new UX);aj(this.a,true);vG(this.b,d,a);WF(d,new OX(0));qG(d,(Kn(),Gn));vG(this.b,this.a,new BX(vn))}
var BTb='co.edu.unal.scrum.client.projects.',zTb='px, ';Kpb(5,6,{10:1,117:1,156:1},Db);_.Dc=function Eb(){};_.Fc=function Fb(){};_.Gc=function Gb(){};_.Hc=function Hb(){nb(this,new oDb((Kc(),Ec),this))};_.a=null;Kpb(11,12,{2:1},Ub);_.Lc=function Vb(){return this.b};_.Jc=function Wb(a,b){if(a===(Bb(),zb)){if(b){VF(this.a);uG(this.a,b)}}};_.a=null;_.b=null;Kpb(14,15,GMb,ac);_.Mc=function bc(a){_b(this,gbb(a,30))};_.a=null;Kpb(45,1,KMb);_.Xc=function Ve(){$Bb(this.b,ge(this.a.a))};Kpb(65,7,DMb,wg);_.Dc=function xg(){};Kpb(66,28,JMb,zg);_.Lc=function Ag(){return this.b};_.a=null;_.b=null;Kpb(384,375,{86:1,89:1},EX);Kpb(385,280,{87:1},GX);_.Mf=function HX(a,b){var c,d,e,g,i,j,k;if(!this.b){ui(a,'x-column-layout-ct');this.b=_q(b,kv("<div class='x-column-inner'><\/div>"));_q(this.b,kv("<div class='x-clear'><\/div>"))}aK(this,a,this.b);j=Cr(b,true);k=j.b-(this.a?(jv(),hv==-1&&(hv=pv()),jv(),hv):0);i=k;d=a.kb.b;for(g=0;g<d;++g){c=g<a.kb.b?gbb(BJb(a.kb,g),55):null;e=gbb(Gi(c,yTb),89);!!e&&ibb(e,86)?gbb(e,86):new EX;i-=UJ(c)}for(g=0;g<d;++g){c=g<a.kb.b?gbb(BJb(a.kb,g),55):null;e=gbb(Gi(c,yTb),89);!!e&&ibb(e,86)?gbb(e,86):new EX;ibb(c,53)?hk(gbb(c,53),-1,-1):c.jc&&ss(TJ(c.Zc()),-1,-1,true)}};_.a=false;_.b=null;Kpb(684,670,HNb);_.Zg=function xxb(){return this.Bc};_.ye=function yxb(){return new Lyb(this)};_.Wg=function zxb(a){return uxb(this,a)};_.r=null;Kpb(683,684,{113:1,117:1,134:1,141:1,142:1,143:1,144:1,145:1,148:1,149:1},Hxb);_.Zg=function Ixb(){return O3(this.Bc)};_.$c=function Jxb(){return !nGb(AOb,this.Bc.style[zOb])};_.gd=function Kxb(){this.p&&$xb(this.o,false,true)};_.a=false;_.b=false;_.c=null;_.e=null;_.f=false;_.g=false;_.i=-1;_.j=false;_.k=null;_.n=false;_.p=false;_.q=-1;Kpb(685,1,kNb,Nxb);_.Hf=function Oxb(a){Mxb()};Kpb(688,211,{},_xb);_.Pe=function ayb(){Xxb(this)};_.Qe=function byb(){this.d=D3(this.a.Bc,ATb);this.e=D3(this.a.Bc,kSb);this.a.Bc.style[XSb]=AOb;Zxb(this,(1+Math.cos(3.141592653589793))/2)};_.Re=function cyb(a){Zxb(this,a)};_.a=null;_.b=false;_.c=false;_.d=0;_.e=-1;_.f=null;_.g=null;_.i=false;Kpb(697,1,{},Lyb);_.Ce=function Myb(){return this.a};_.De=function Nyb(){return Kyb(this)};_.Ee=function Oyb(){!!this.b&&uxb(this.c,this.b)};_.b=null;_.c=null;var sbb=mEb(MQb,'HomePresenter',5),tbb=mEb(MQb,'HomeView$1',14),lcb=mEb(BTb,'TeamEditorPresenter',65),mcb=mEb(BTb,'TeamEditorView',66),shb=mEb(CTb,'ColumnLayout',385),Alb=mEb(oRb,'SimplePanel',684),slb=mEb(oRb,'PopupPanel',683),rlb=mEb(oRb,'PopupPanel$ResizeAnimation',688),nlb=mEb(oRb,'PopupPanel$1',685),zlb=mEb(oRb,'SimplePanel$1',697),rhb=mEb(CTb,'ColumnData',384);UNb(S1)(5);