function EX(){}
function nxb(){}
function NU(a,b){a.g=b}
function Ud(a,b){a.Dc(b)}
function _d(a,b){a.Dc(b)}
function ac(a){this.b=a}
function Ywb(a){this.Cc=a}
function Cb(a){kb(a,a.b)}
function wg(a,b){ub.call(this,a,b)}
function Bxb(a){HA.call(this);this.b=a}
function lyb(a){this.d=a;this.b=!!this.d.s}
function _b(a){!!a.b.n&&Cb(Uab(a.b.n,10))}
function Od(){return new zg}
function GX(){fK.call(this);this.u=iTb;this.v=true}
function Db(a,b,c){Bb();ub.call(this,a,b);this.b=c;Uab(this.i,2).Lc(this)}
function kyb(a){if(!a.b||!a.d.s){throw new DLb}a.b=false;return a.c=a.d.s}
function Vwb(a,b){if(a.s){throw new BEb('SimplePanel can only contain one child widget')}Xwb(a,b)}
function Wwb(a,b){if(a.s!=b){return false}try{gi(b,null)}finally{z3(a.Ug(),b.$c());a.s=null}return true}
function Xwb(a,b){if(b==a.s){return}!!b&&(Wab(b.Bc,57)&&Uab(b.Bc,57).wf(b),ei(b));!!a.s&&Wwb(a,a.s);a.s=b;if(b){krb(O3(a.Cc),Hi(a.s));gi(b,a)}}
function zxb(a,b){var c,d,e,g,i,j;a.j||(b=1-b);i=0;e=0;g=0;c=0;d=$ab(b*a.e);j=$ab(b*a.f);switch(0){case 2:case 0:i=a.e-d>>1;e=a.f-j>>1;g=e+j;c=i+d;}Uyb(a.b.Cc,'rect('+i+kTb+g+kTb+c+kTb+e+'px)')}
function hxb(){Ywb.call(this,$doc.createElement(FNb));this.e=new nxb;this.p=new Bxb(this);w3(this.Cc,$doc.createElement(FNb));exb(this,0,0);P3(O3(this.Cc))[gOb]='gwt-PopupPanel';O3(this.Cc)[gOb]='popupContent'}
function ge(a){var b,c;!a.c&&(a.c=(b=new Db((!a.C&&(a.C=new W6),a.C),(!a.d&&(a.d=new Ub(new Og)),a.d),(!a.b&&(a.b=new Nb),c=new wg((!a.C&&(a.C=new W6),a.C),Od(!a.C&&(a.C=new W6))),_d(c,(!a.F&&(a.F=new rAb),a.F)),c)),Ud(b,(!a.F&&(a.F=new rAb),a.F)),b));return a.c}
function zg(){var a,b,c,d;this.c=new hxb;new jJb;this.c.k=true;this.c.c=true;this.c.b=true;this.c.g=true;this.b=new QU;hk(this.b,800,-1);NU(this.b,(eV(),dV));aH(this.b,(gn(),dn));d=new EG(new GX);a=Uab(d.mb,87);a.b=true;d.Nb=1;d.kc&&fs(Qs(Hi(d),mRb),true);c=new DG;b=new fY;eY(b,dV);WF(c,b);Vwb(this.c,this.b)}
function Ub(){var a,b,c,d,e,g;this.c=new EG(new $W);aj(this.c,true);hj(this.c,gbb.e);d=new dH;d.Ff('Projects');a=new BX((An(),zn));a.b=true;a.g=true;g=new fQ;g.Nb=1;g.kc&&fs(Qs(Hi(g),mRb),true);g.tb=true;g.sb=true;b=new EP('Add',_vb((Pg(),Ng(),Dg)));pP(b,new ac(this));bQ(g,b,g.lb.c);e=new x0;e.Nb=1;e.kc&&fs(Qs(Hi(e),mRb),true);bQ(g,e,g.lb.c);c=new EP(ASb,_vb((Rg(),Fg)));bQ(g,c,g.lb.c);xG(d,g,d.lb.c);this.b=new DG;WF(this.b,new UX);aj(this.b,true);vG(this.c,d,a);WF(d,new OX(0));qG(d,(Kn(),Gn));vG(this.c,this.b,new BX(vn))}
var mTb='co.edu.unal.scrum.client.projects.',kTb='px, ';vpb(5,6,{10:1,117:1,156:1},Db);_.Ec=function Eb(){};_.Gc=function Fb(){};_.Hc=function Gb(){};_.Ic=function Hb(){nb(this,new QCb((Kc(),Ec),this))};_.b=null;vpb(11,12,{2:1},Ub);_.Mc=function Vb(){return this.c};_.Kc=function Wb(a,b){if(a===(Bb(),zb)){if(b){VF(this.b);uG(this.b,b)}}};_.b=null;_.c=null;vpb(14,15,gMb,ac);_.Nc=function bc(a){_b(this,Uab(a,30))};_.b=null;vpb(45,1,kMb);_.Yc=function Ve(){ABb(this.c,ge(this.b.b))};vpb(65,7,dMb,wg);_.Ec=function xg(){};vpb(66,28,jMb,zg);_.Mc=function Ag(){return this.c};_.b=null;_.c=null;vpb(384,375,{86:1,89:1},EX);vpb(385,280,{87:1},GX);_.Nf=function HX(a,b){var c,d,e,g,i,j,k;if(!this.c){ui(a,'x-column-layout-ct');this.c=_q(b,kv("<div class='x-column-inner'><\/div>"));_q(this.c,kv("<div class='x-clear'><\/div>"))}aK(this,a,this.c);j=Cr(b,true);k=j.c-(this.b?(jv(),hv==-1&&(hv=pv()),jv(),hv):0);i=k;d=a.lb.c;for(g=0;g<d;++g){c=g<a.lb.c?Uab(bJb(a.lb,g),55):null;e=Uab(Gi(c,jTb),89);!!e&&Wab(e,86)?Uab(e,86):new EX;i-=UJ(c)}for(g=0;g<d;++g){c=g<a.lb.c?Uab(bJb(a.lb,g),55):null;e=Uab(Gi(c,jTb),89);!!e&&Wab(e,86)?Uab(e,86):new EX;Wab(c,53)?hk(Uab(c,53),-1,-1):c.kc&&ss(TJ(c.$c()),-1,-1,true)}};_.b=false;_.c=null;vpb(680,666,hNb);_.Ug=function Zwb(){return this.Cc};_.ze=function $wb(){return new lyb(this)};_.Rg=function _wb(a){return Wwb(this,a)};_.s=null;vpb(679,680,{113:1,117:1,134:1,141:1,142:1,143:1,144:1,145:1,148:1,149:1},hxb);_.Ug=function ixb(){return O3(this.Cc)};_._c=function jxb(){return !PFb(aOb,this.Cc.style[_Nb])};_.hd=function kxb(){this.q&&Axb(this.p,false,true)};_.b=false;_.c=false;_.d=null;_.f=null;_.g=false;_.i=false;_.j=-1;_.k=false;_.n=null;_.o=false;_.q=false;_.r=-1;vpb(681,1,MMb,nxb);_.If=function oxb(a){mxb()};vpb(684,211,{},Bxb);_.Qe=function Cxb(){xxb(this)};_.Re=function Dxb(){this.e=D3(this.b.Cc,lTb);this.f=D3(this.b.Cc,XRb);this.b.Cc.style[ISb]=aOb;zxb(this,(1+Math.cos(3.141592653589793))/2)};_.Se=function Exb(a){zxb(this,a)};_.b=null;_.c=false;_.d=false;_.e=0;_.f=-1;_.g=null;_.i=null;_.j=false;vpb(693,1,{},lyb);_.De=function myb(){return this.b};_.Ee=function nyb(){return kyb(this)};_.Fe=function oyb(){!!this.c&&Wwb(this.d,this.c)};_.c=null;_.d=null;var ebb=ODb(xQb,'HomePresenter',5),fbb=ODb(xQb,'HomeView$1',14),Zbb=ODb(mTb,'TeamEditorPresenter',65),$bb=ODb(mTb,'TeamEditorView',66),ehb=ODb(nTb,'ColumnLayout',385),llb=ODb(_Qb,'SimplePanel',680),dlb=ODb(_Qb,'PopupPanel',679),clb=ODb(_Qb,'PopupPanel$ResizeAnimation',684),$kb=ODb(_Qb,'PopupPanel$1',681),klb=ODb(_Qb,'SimplePanel$1',693),dhb=ODb(nTb,'ColumnData',384);uNb(S1)(5);