function FX(){}
function Ixb(){}
function OU(a,b){a.f=b}
function Ud(a,b){a.Cc(b)}
function _d(a,b){a.Cc(b)}
function ac(a){this.a=a}
function rxb(a){this.Bc=a}
function Cb(a){kb(a,a.a)}
function Od(){return new zg}
function wg(a,b){ub.call(this,a,b)}
function Wxb(a){IA.call(this);this.a=a}
function Gyb(a){this.c=a;this.a=!!this.c.r}
function HX(){gK.call(this);this.t=ITb;this.u=true}
function _b(a){!!a.a.k&&Cb(ebb(a.a.k,10))}
function Fyb(a){if(!a.a||!a.c.r){throw new YLb}a.a=false;return a.b=a.c.r}
function Db(a,b,c){Bb();ub.call(this,a,b);this.a=c;ebb(this.g,2).Kc(this)}
function oxb(a,b){if(a.r){throw new WEb('SimplePanel can only contain one child widget')}qxb(a,b)}
function pxb(a,b){if(a.r!=b){return false}try{gi(b,null)}finally{A3(a.Ug(),b.Zc());a.r=null}return true}
function qxb(a,b){if(b==a.r){return}!!b&&(gbb(b.Ac,57)&&ebb(b.Ac,57).vf(b),ei(b));!!a.r&&pxb(a,a.r);a.r=b;if(b){Drb(P3(a.Bc),Hi(a.r));gi(b,a)}}
function Cxb(){rxb.call(this,S3($doc,$Nb));this.d=new Ixb;this.o=new Wxb(this);x3(this.Bc,S3($doc,$Nb));zxb(this,0,0);Q3(P3(this.Bc))[BOb]='gwt-PopupPanel';P3(this.Bc)[BOb]='popupContent'}
function Uxb(a,b){var c,d,e,g,i,j;a.i||(b=1-b);i=0;e=0;g=0;c=0;d=kbb(b*a.d);j=kbb(b*a.e);switch(0){case 2:case 0:i=a.d-d>>1;e=a.e-j>>1;g=e+j;c=i+d;}nzb(a.a.Bc,'rect('+i+KTb+g+KTb+c+KTb+e+'px)')}
function ge(a){var b,c;!a.b&&(a.b=(b=new Db((!a.B&&(a.B=new g7),a.B),(!a.c&&(a.c=new Ub(new Og)),a.c),(!a.a&&(a.a=new Nb),c=new wg((!a.B&&(a.B=new g7),a.B),Od(!a.B&&(a.B=new g7))),_d(c,(!a.E&&(a.E=new MAb),a.E)),c)),Ud(b,(!a.E&&(a.E=new MAb),a.E)),b));return a.b}
function zg(){var a,b,c,d;this.b=new Cxb;new EJb;this.b.j=true;this.b.b=true;this.b.a=true;this.b.f=true;this.a=new RU;hk(this.a,800,-1);OU(this.a,(fV(),eV));bH(this.a,(gn(),dn));d=new FG(new HX);a=ebb(d.lb,87);a.a=true;d.Mb=1;d.jc&&fs(Qs(Hi(d),MRb),true);c=new EG;b=new gY;fY(b,eV);XF(c,b);oxb(this.b,this.a)}
function Ub(){var a,b,c,d,e,g;this.b=new FG(new _W);aj(this.b,true);hj(this.b,sbb.d);d=new eH;d.Ef('Projects');a=new CX((An(),zn));a.a=true;a.f=true;g=new gQ;g.Mb=1;g.jc&&fs(Qs(Hi(g),MRb),true);g.sb=true;g.rb=true;b=new FP('Add',uwb((Pg(),Ng(),Dg)));qP(b,new ac(this));cQ(g,b,g.kb.b);e=new y0;e.Mb=1;e.jc&&fs(Qs(Hi(e),MRb),true);cQ(g,e,g.kb.b);c=new FP($Sb,uwb((Rg(),Fg)));cQ(g,c,g.kb.b);yG(d,g,d.kb.b);this.a=new EG;XF(this.a,new VX);aj(this.a,true);wG(this.b,d,a);XF(d,new PX(0));rG(d,(Kn(),Gn));wG(this.b,this.a,new CX(vn))}
var MTb='co.edu.unal.scrum.client.projects.',KTb='px, ';Jpb(5,6,{10:1,117:1,156:1},Db);_.Dc=function Eb(){};_.Fc=function Fb(){};_.Gc=function Gb(){};_.Hc=function Hb(){nb(this,new jDb((Kc(),Ec),this))};_.a=null;Jpb(11,12,{2:1},Ub);_.Lc=function Vb(){return this.b};_.Jc=function Wb(a,b){if(a===(Bb(),zb)){if(b){WF(this.a);vG(this.a,b)}}};_.a=null;_.b=null;Jpb(14,15,BMb,ac);_.Mc=function bc(a){_b(this,ebb(a,30))};_.a=null;Jpb(45,1,FMb);_.Xc=function Ve(){VBb(this.b,ge(this.a.a))};Jpb(65,7,yMb,wg);_.Dc=function xg(){};Jpb(66,28,EMb,zg);_.Lc=function Ag(){return this.b};_.a=null;_.b=null;Jpb(385,376,{86:1,89:1},FX);Jpb(386,281,{87:1},HX);_.Mf=function IX(a,b){var c,d,e,g,i,j,k;if(!this.b){ui(a,'x-column-layout-ct');this.b=_q(b,kv("<div class='x-column-inner'><\/div>"));_q(this.b,kv("<div class='x-clear'><\/div>"))}bK(this,a,this.b);j=Cr(b,true);k=j.b-(this.a?(jv(),hv==-1&&(hv=pv()),jv(),hv):0);i=k;d=a.kb.b;for(g=0;g<d;++g){c=g<a.kb.b?ebb(wJb(a.kb,g),55):null;e=ebb(Gi(c,JTb),89);!!e&&gbb(e,86)?ebb(e,86):new FX;i-=VJ(c)}for(g=0;g<d;++g){c=g<a.kb.b?ebb(wJb(a.kb,g),55):null;e=ebb(Gi(c,JTb),89);!!e&&gbb(e,86)?ebb(e,86):new FX;gbb(c,53)?hk(ebb(c,53),-1,-1):c.jc&&ss(UJ(c.Zc()),-1,-1,true)}};_.a=false;_.b=null;Jpb(682,668,CNb);_.Ug=function sxb(){return this.Bc};_.ye=function txb(){return new Gyb(this)};_.Rg=function uxb(a){return pxb(this,a)};_.r=null;Jpb(681,682,{113:1,117:1,134:1,141:1,142:1,143:1,144:1,145:1,148:1,149:1},Cxb);_.Ug=function Dxb(){return P3(this.Bc)};_.$c=function Exb(){return !iGb(vOb,this.Bc.style[uOb])};_.gd=function Fxb(){this.p&&Vxb(this.o,false,true)};_.a=false;_.b=false;_.c=null;_.e=null;_.f=false;_.g=false;_.i=-1;_.j=false;_.k=null;_.n=false;_.p=false;_.q=-1;Jpb(683,1,fNb,Ixb);_.Hf=function Jxb(a){Hxb()};Jpb(686,212,{},Wxb);_.Pe=function Xxb(){Sxb(this)};_.Qe=function Yxb(){this.d=E3(this.a.Bc,LTb);this.e=E3(this.a.Bc,vSb);this.a.Bc.style[hTb]=vOb;Uxb(this,(1+Math.cos(3.141592653589793))/2)};_.Re=function Zxb(a){Uxb(this,a)};_.a=null;_.b=false;_.c=false;_.d=0;_.e=-1;_.f=null;_.g=null;_.i=false;Jpb(695,1,{},Gyb);_.Ce=function Hyb(){return this.a};_.De=function Iyb(){return Fyb(this)};_.Ee=function Jyb(){!!this.b&&pxb(this.c,this.b)};_.b=null;_.c=null;var qbb=hEb(WQb,'HomePresenter',5),rbb=hEb(WQb,'HomeView$1',14),jcb=hEb(MTb,'TeamEditorPresenter',65),kcb=hEb(MTb,'TeamEditorView',66),rhb=hEb(NTb,'ColumnLayout',386),zlb=hEb(yRb,'SimplePanel',682),rlb=hEb(yRb,'PopupPanel',681),qlb=hEb(yRb,'PopupPanel$ResizeAnimation',686),mlb=hEb(yRb,'PopupPanel$1',683),ylb=hEb(yRb,'SimplePanel$1',695),qhb=hEb(NTb,'ColumnData',385);PNb(T1)(5);