function FX(){}
function Sxb(){}
function OU(a,b){a.f=b}
function Ud(a,b){a.Cc(b)}
function _d(a,b){a.Cc(b)}
function ac(a){this.a=a}
function Bxb(a){this.Bc=a}
function Cb(a){kb(a,a.a)}
function Od(){return new zg}
function wg(a,b){ub.call(this,a,b)}
function eyb(a){IA.call(this);this.a=a}
function Qyb(a){this.c=a;this.a=!!this.c.r}
function HX(){gK.call(this);this.t=HTb;this.u=true}
function _b(a){!!a.a.k&&Cb(obb(a.a.k,10))}
function Pyb(a){if(!a.a||!a.c.r){throw new gMb}a.a=false;return a.b=a.c.r}
function Db(a,b,c){Bb();ub.call(this,a,b);this.a=c;obb(this.g,2).Kc(this)}
function yxb(a,b){if(a.r){throw new eFb('SimplePanel can only contain one child widget')}Axb(a,b)}
function zxb(a,b){if(a.r!=b){return false}try{gi(b,null)}finally{A3(a.Zg(),b.Zc());a.r=null}return true}
function Axb(a,b){if(b==a.r){return}!!b&&(qbb(b.Ac,57)&&obb(b.Ac,57).vf(b),ei(b));!!a.r&&zxb(a,a.r);a.r=b;if(b){Nrb(P3(a.Bc),Hi(a.r));gi(b,a)}}
function Mxb(){Bxb.call(this,S3($doc,iOb));this.d=new Sxb;this.o=new eyb(this);x3(this.Bc,S3($doc,iOb));Jxb(this,0,0);Q3(P3(this.Bc))[LOb]='gwt-PopupPanel';P3(this.Bc)[LOb]='popupContent'}
function cyb(a,b){var c,d,e,g,i,j;a.i||(b=1-b);i=0;e=0;g=0;c=0;d=ubb(b*a.d);j=ubb(b*a.e);switch(0){case 2:case 0:i=a.d-d>>1;e=a.e-j>>1;g=e+j;c=i+d;}xzb(a.a.Bc,'rect('+i+JTb+g+JTb+c+JTb+e+'px)')}
function ge(a){var b,c;!a.b&&(a.b=(b=new Db((!a.B&&(a.B=new g7),a.B),(!a.c&&(a.c=new Ub(new Og)),a.c),(!a.a&&(a.a=new Nb),c=new wg((!a.B&&(a.B=new g7),a.B),Od(!a.B&&(a.B=new g7))),_d(c,(!a.E&&(a.E=new WAb),a.E)),c)),Ud(b,(!a.E&&(a.E=new WAb),a.E)),b));return a.b}
function zg(){var a,b,c,d;this.b=new Mxb;new OJb;this.b.j=true;this.b.b=true;this.b.a=true;this.b.f=true;this.a=new RU;hk(this.a,800,-1);OU(this.a,(fV(),eV));bH(this.a,(gn(),dn));d=new FG(new HX);a=obb(d.lb,87);a.a=true;d.Mb=1;d.jc&&fs(Qs(Hi(d),LRb),true);c=new EG;b=new gY;fY(b,eV);XF(c,b);yxb(this.b,this.a)}
function Ub(){var a,b,c,d,e,g;this.b=new FG(new _W);aj(this.b,true);hj(this.b,Cbb.d);d=new eH;d.Ef('Projects');a=new CX((An(),zn));a.a=true;a.f=true;g=new gQ;g.Mb=1;g.jc&&fs(Qs(Hi(g),LRb),true);g.sb=true;g.rb=true;b=new FP('Add',Ewb((Pg(),Ng(),Dg)));qP(b,new ac(this));cQ(g,b,g.kb.b);e=new y0;e.Mb=1;e.jc&&fs(Qs(Hi(e),LRb),true);cQ(g,e,g.kb.b);c=new FP(ZSb,Ewb((Rg(),Fg)));cQ(g,c,g.kb.b);yG(d,g,d.kb.b);this.a=new EG;XF(this.a,new VX);aj(this.a,true);wG(this.b,d,a);XF(d,new PX(0));rG(d,(Kn(),Gn));wG(this.b,this.a,new CX(vn))}
var LTb='co.edu.unal.scrum.client.projects.',JTb='px, ';Tpb(5,6,{10:1,117:1,156:1},Db);_.Dc=function Eb(){};_.Fc=function Fb(){};_.Gc=function Gb(){};_.Hc=function Hb(){nb(this,new tDb((Kc(),Ec),this))};_.a=null;Tpb(11,12,{2:1},Ub);_.Lc=function Vb(){return this.b};_.Jc=function Wb(a,b){if(a===(Bb(),zb)){if(b){WF(this.a);vG(this.a,b)}}};_.a=null;_.b=null;Tpb(14,15,LMb,ac);_.Mc=function bc(a){_b(this,obb(a,30))};_.a=null;Tpb(45,1,PMb);_.Xc=function Ve(){dCb(this.b,ge(this.a.a))};Tpb(65,7,IMb,wg);_.Dc=function xg(){};Tpb(66,28,OMb,zg);_.Lc=function Ag(){return this.b};_.a=null;_.b=null;Tpb(385,376,{86:1,89:1},FX);Tpb(386,281,{87:1},HX);_.Mf=function IX(a,b){var c,d,e,g,i,j,k;if(!this.b){ui(a,'x-column-layout-ct');this.b=_q(b,kv("<div class='x-column-inner'><\/div>"));_q(this.b,kv("<div class='x-clear'><\/div>"))}bK(this,a,this.b);j=Cr(b,true);k=j.b-(this.a?(jv(),hv==-1&&(hv=pv()),jv(),hv):0);i=k;d=a.kb.b;for(g=0;g<d;++g){c=g<a.kb.b?obb(GJb(a.kb,g),55):null;e=obb(Gi(c,ITb),89);!!e&&qbb(e,86)?obb(e,86):new FX;i-=VJ(c)}for(g=0;g<d;++g){c=g<a.kb.b?obb(GJb(a.kb,g),55):null;e=obb(Gi(c,ITb),89);!!e&&qbb(e,86)?obb(e,86):new FX;qbb(c,53)?hk(obb(c,53),-1,-1):c.jc&&ss(UJ(c.Zc()),-1,-1,true)}};_.a=false;_.b=null;Tpb(682,668,MNb);_.Zg=function Cxb(){return this.Bc};_.ye=function Dxb(){return new Qyb(this)};_.Wg=function Exb(a){return zxb(this,a)};_.r=null;Tpb(681,682,{113:1,117:1,134:1,141:1,142:1,143:1,144:1,145:1,148:1,149:1},Mxb);_.Zg=function Nxb(){return P3(this.Bc)};_.$c=function Oxb(){return !sGb(FOb,this.Bc.style[EOb])};_.gd=function Pxb(){this.p&&dyb(this.o,false,true)};_.a=false;_.b=false;_.c=null;_.e=null;_.f=false;_.g=false;_.i=-1;_.j=false;_.k=null;_.n=false;_.p=false;_.q=-1;Tpb(683,1,pNb,Sxb);_.Hf=function Txb(a){Rxb()};Tpb(686,212,{},eyb);_.Pe=function fyb(){ayb(this)};_.Qe=function gyb(){this.d=E3(this.a.Bc,KTb);this.e=E3(this.a.Bc,uSb);this.a.Bc.style[gTb]=FOb;cyb(this,(1+Math.cos(3.141592653589793))/2)};_.Re=function hyb(a){cyb(this,a)};_.a=null;_.b=false;_.c=false;_.d=0;_.e=-1;_.f=null;_.g=null;_.i=false;Tpb(695,1,{},Qyb);_.Ce=function Ryb(){return this.a};_.De=function Syb(){return Pyb(this)};_.Ee=function Tyb(){!!this.b&&zxb(this.c,this.b)};_.b=null;_.c=null;var Abb=rEb(VQb,'HomePresenter',5),Bbb=rEb(VQb,'HomeView$1',14),tcb=rEb(LTb,'TeamEditorPresenter',65),ucb=rEb(LTb,'TeamEditorView',66),Bhb=rEb(MTb,'ColumnLayout',386),Jlb=rEb(xRb,'SimplePanel',682),Blb=rEb(xRb,'PopupPanel',681),Alb=rEb(xRb,'PopupPanel$ResizeAnimation',686),wlb=rEb(xRb,'PopupPanel$1',683),Ilb=rEb(xRb,'SimplePanel$1',695),Ahb=rEb(MTb,'ColumnData',385);ZNb(T1)(5);