function FX(){}
function fyb(){}
function OU(a,b){a.g=b}
function Ud(a,b){a.Dc(b)}
function _d(a,b){a.Dc(b)}
function ac(a){this.b=a}
function Qxb(a){this.Cc=a}
function Cb(a){kb(a,a.b)}
function wg(a,b){ub.call(this,a,b)}
function tyb(a){IA.call(this);this.b=a}
function dzb(a){this.d=a;this.b=!!this.d.s}
function _b(a){!!a.b.n&&Cb(Fbb(a.b.n,10))}
function Od(){return new zg}
function HX(){gK.call(this);this.u=gUb;this.v=true}
function Db(a,b,c){Bb();ub.call(this,a,b);this.b=c;Fbb(this.i,2).Lc(this)}
function czb(a){if(!a.b||!a.d.s){throw new xMb}a.b=false;return a.c=a.d.s}
function Nxb(a,b){if(a.s){throw new tFb('SimplePanel can only contain one child widget')}Pxb(a,b)}
function Oxb(a,b){if(a.s!=b){return false}try{gi(b,null)}finally{h4(a.ah(),b.$c());a.s=null}return true}
function Pxb(a,b){if(b==a.s){return}!!b&&(Hbb(b.Bc,57)&&Fbb(b.Bc,57).wf(b),ei(b));!!a.s&&Oxb(a,a.s);a.s=b;if(b){bsb(w4(a.Cc),Hi(a.s));gi(b,a)}}
function ryb(a,b){var c,d,e,g,i,j;a.j||(b=1-b);i=0;e=0;g=0;c=0;d=Lbb(b*a.e);j=Lbb(b*a.f);switch(0){case 2:case 0:i=~~(a.e-d)>>1;e=~~(a.f-j)>>1;g=e+j;c=i+d;}Mzb(a.b.Cc,'rect('+i+iUb+g+iUb+c+iUb+e+'px)')}
function _xb(){Qxb.call(this,$doc.createElement(AOb));this.e=new fyb;this.p=new tyb(this);e4(this.Cc,$doc.createElement(AOb));Yxb(this,0,0);x4(w4(this.Cc))[bPb]='gwt-PopupPanel';w4(this.Cc)[bPb]='popupContent'}
function ge(a){var b,c;!a.c&&(a.c=(b=new Db((!a.C&&(a.C=new I7),a.C),(!a.d&&(a.d=new Ub(new Og)),a.d),(!a.b&&(a.b=new Nb),c=new wg((!a.C&&(a.C=new I7),a.C),Od(!a.C&&(a.C=new I7))),_d(c,(!a.F&&(a.F=new jBb),a.F)),c)),Ud(b,(!a.F&&(a.F=new jBb),a.F)),b));return a.c}
function zg(){var a,b,c,d;this.c=new _xb;new dKb;this.c.k=true;this.c.c=true;this.c.b=true;this.c.g=true;this.b=new RU;hk(this.b,800,-1);OU(this.b,(fV(),eV));bH(this.b,(gn(),dn));d=new FG(new HX);a=Fbb(d.mb,87);a.b=true;d.Nb=1;d.kc&&fs(Qs(Hi(d),kSb),true);c=new EG;b=new gY;fY(b,eV);XF(c,b);Nxb(this.c,this.b)}
function Ub(){var a,b,c,d,e,g;this.c=new FG(new _W);aj(this.c,true);hj(this.c,Tbb.e);d=new eH;d.Ff('Projects');a=new CX((An(),zn));a.b=true;a.g=true;g=new gQ;g.Nb=1;g.kc&&fs(Qs(Hi(g),kSb),true);g.tb=true;g.sb=true;b=new FP('Add',Twb((Pg(),Ng(),Dg)));qP(b,new ac(this));cQ(g,b,g.lb.c);e=new y0;e.Nb=1;e.kc&&fs(Qs(Hi(e),kSb),true);cQ(g,e,g.lb.c);c=new FP(yTb,Twb((Rg(),Fg)));cQ(g,c,g.lb.c);yG(d,g,d.lb.c);this.b=new EG;XF(this.b,new VX);aj(this.b,true);wG(this.c,d,a);XF(d,new PX(0));rG(d,(Kn(),Gn));wG(this.c,this.b,new CX(vn))}
var kUb='co.edu.unal.scrum.client.projects.',iUb='px, ';mqb(5,6,{10:1,117:1,156:1},Db);_.Ec=function Eb(){};_.Gc=function Fb(){};_.Hc=function Gb(){};_.Ic=function Hb(){nb(this,new IDb((Kc(),Ec),this))};_.b=null;mqb(11,12,{2:1},Ub);_.Mc=function Vb(){return this.c};_.Kc=function Wb(a,b){if(a===(Bb(),zb)){if(b){WF(this.b);vG(this.b,b)}}};_.b=null;_.c=null;mqb(14,15,aNb,ac);_.Nc=function bc(a){_b(this,Fbb(a,30))};_.b=null;mqb(45,1,eNb);_.Yc=function Ve(){sCb(this.c,ge(this.b.b))};mqb(65,7,ZMb,wg);_.Ec=function xg(){};mqb(66,28,dNb,zg);_.Mc=function Ag(){return this.c};_.b=null;_.c=null;mqb(384,375,{86:1,89:1},FX);mqb(385,280,{87:1},HX);_.Nf=function IX(a,b){var c,d,e,g,i,j,k;if(!this.c){ui(a,'x-column-layout-ct');this.c=_q(b,kv("<div class='x-column-inner'><\/div>"));_q(this.c,kv("<div class='x-clear'><\/div>"))}bK(this,a,this.c);j=Cr(b,true);k=j.c-(this.b?(jv(),hv==-1&&(hv=pv()),jv(),hv):0);i=k;d=a.lb.c;for(g=0;g<d;++g){c=g<a.lb.c?Fbb(XJb(a.lb,g),55):null;e=Fbb(Gi(c,hUb),89);!!e&&Hbb(e,86)?Fbb(e,86):new FX;i-=VJ(c)}for(g=0;g<d;++g){c=g<a.lb.c?Fbb(XJb(a.lb,g),55):null;e=Fbb(Gi(c,hUb),89);!!e&&Hbb(e,86)?Fbb(e,86):new FX;Hbb(c,53)?hk(Fbb(c,53),-1,-1):c.kc&&ss(UJ(c.$c()),-1,-1,true)}};_.b=false;_.c=null;mqb(683,669,cOb);_.ah=function Rxb(){return this.Cc};_.ze=function Sxb(){return new dzb(this)};_.Zg=function Txb(a){return Oxb(this,a)};_.s=null;mqb(682,683,{113:1,117:1,134:1,141:1,142:1,143:1,144:1,145:1,148:1,149:1},_xb);_.ah=function ayb(){return w4(this.Cc)};_._c=function byb(){return !HGb(XOb,this.Cc.style[WOb])};_.hd=function cyb(){this.q&&syb(this.p,false,true)};_.b=false;_.c=false;_.d=null;_.f=null;_.g=false;_.i=false;_.j=-1;_.k=false;_.n=null;_.o=false;_.q=false;_.r=-1;mqb(684,1,GNb,fyb);_.If=function gyb(a){eyb()};mqb(687,211,{},tyb);_.Qe=function uyb(){pyb(this)};_.Re=function vyb(){this.e=l4(this.b.Cc,jUb);this.f=l4(this.b.Cc,VSb);this.b.Cc.style[GTb]=XOb;ryb(this,(1+Math.cos(3.141592653589793))/2)};_.Se=function wyb(a){ryb(this,a)};_.b=null;_.c=false;_.d=false;_.e=0;_.f=-1;_.g=null;_.i=null;_.j=false;mqb(696,1,{},dzb);_.De=function ezb(){return this.b};_.Ee=function fzb(){return czb(this)};_.Fe=function gzb(){!!this.c&&Oxb(this.d,this.c)};_.c=null;_.d=null;var Rbb=GEb(vRb,'HomePresenter',5),Sbb=GEb(vRb,'HomeView$1',14),Kcb=GEb(kUb,'TeamEditorPresenter',65),Lcb=GEb(kUb,'TeamEditorView',66),Rhb=GEb(lUb,'ColumnLayout',385),cmb=GEb(ZRb,'SimplePanel',683),Wlb=GEb(ZRb,'PopupPanel',682),Vlb=GEb(ZRb,'PopupPanel$ResizeAnimation',687),Rlb=GEb(ZRb,'PopupPanel$1',684),bmb=GEb(ZRb,'SimplePanel$1',696),Qhb=GEb(lUb,'ColumnData',384);pOb(e2)(5);