function EX(){}
function Bxb(){}
function NU(a,b){a.f=b}
function Ud(a,b){a.Cc(b)}
function _d(a,b){a.Cc(b)}
function ac(a){this.a=a}
function kxb(a){this.Bc=a}
function Cb(a){kb(a,a.a)}
function Od(){return new zg}
function wg(a,b){ub.call(this,a,b)}
function Pxb(a){HA.call(this);this.a=a}
function zyb(a){this.c=a;this.a=!!this.c.r}
function GX(){fK.call(this);this.t=wTb;this.u=true}
function _b(a){!!a.a.k&&Cb(Xab(a.a.k,10))}
function Db(a,b,c){Bb();ub.call(this,a,b);this.a=c;Xab(this.g,2).Kc(this)}
function yyb(a){if(!a.a||!a.c.r){throw new RLb}a.a=false;return a.b=a.c.r}
function hxb(a,b){if(a.r){throw new PEb('SimplePanel can only contain one child widget')}jxb(a,b)}
function ixb(a,b){if(a.r!=b){return false}try{gi(b,null)}finally{z3(a.Ug(),b.Zc());a.r=null}return true}
function jxb(a,b){if(b==a.r){return}!!b&&(Zab(b.Ac,57)&&Xab(b.Ac,57).vf(b),ei(b));!!a.r&&ixb(a,a.r);a.r=b;if(b){srb(O3(a.Bc),Hi(a.r));gi(b,a)}}
function Nxb(a,b){var c,d,e,g,i,j;a.i||(b=1-b);i=0;e=0;g=0;c=0;d=bbb(b*a.d);j=bbb(b*a.e);switch(0){case 2:case 0:i=a.d-d>>1;e=a.e-j>>1;g=e+j;c=i+d;}gzb(a.a.Bc,'rect('+i+yTb+g+yTb+c+yTb+e+'px)')}
function vxb(){kxb.call(this,$doc.createElement(TNb));this.d=new Bxb;this.o=new Pxb(this);w3(this.Bc,$doc.createElement(TNb));sxb(this,0,0);P3(O3(this.Bc))[uOb]='gwt-PopupPanel';O3(this.Bc)[uOb]='popupContent'}
function ge(a){var b,c;!a.b&&(a.b=(b=new Db((!a.B&&(a.B=new $6),a.B),(!a.c&&(a.c=new Ub(new Og)),a.c),(!a.a&&(a.a=new Nb),c=new wg((!a.B&&(a.B=new $6),a.B),Od(!a.B&&(a.B=new $6))),_d(c,(!a.E&&(a.E=new FAb),a.E)),c)),Ud(b,(!a.E&&(a.E=new FAb),a.E)),b));return a.b}
function zg(){var a,b,c,d;this.b=new vxb;new xJb;this.b.j=true;this.b.b=true;this.b.a=true;this.b.f=true;this.a=new QU;hk(this.a,800,-1);NU(this.a,(eV(),dV));aH(this.a,(gn(),dn));d=new EG(new GX);a=Xab(d.lb,87);a.a=true;d.Mb=1;d.jc&&fs(Qs(Hi(d),ARb),true);c=new DG;b=new fY;eY(b,dV);WF(c,b);hxb(this.b,this.a)}
function Ub(){var a,b,c,d,e,g;this.b=new EG(new $W);aj(this.b,true);hj(this.b,jbb.d);d=new dH;d.Ef('Projects');a=new BX((An(),zn));a.a=true;a.f=true;g=new fQ;g.Mb=1;g.jc&&fs(Qs(Hi(g),ARb),true);g.sb=true;g.rb=true;b=new EP('Add',nwb((Pg(),Ng(),Dg)));pP(b,new ac(this));bQ(g,b,g.kb.b);e=new x0;e.Mb=1;e.jc&&fs(Qs(Hi(e),ARb),true);bQ(g,e,g.kb.b);c=new EP(OSb,nwb((Rg(),Fg)));bQ(g,c,g.kb.b);xG(d,g,d.kb.b);this.a=new DG;WF(this.a,new UX);aj(this.a,true);vG(this.b,d,a);WF(d,new OX(0));qG(d,(Kn(),Gn));vG(this.b,this.a,new BX(vn))}
var ATb='co.edu.unal.scrum.client.projects.',yTb='px, ';ypb(5,6,{10:1,117:1,156:1},Db);_.Dc=function Eb(){};_.Fc=function Fb(){};_.Gc=function Gb(){};_.Hc=function Hb(){nb(this,new cDb((Kc(),Ec),this))};_.a=null;ypb(11,12,{2:1},Ub);_.Lc=function Vb(){return this.b};_.Jc=function Wb(a,b){if(a===(Bb(),zb)){if(b){VF(this.a);uG(this.a,b)}}};_.a=null;_.b=null;ypb(14,15,uMb,ac);_.Mc=function bc(a){_b(this,Xab(a,30))};_.a=null;ypb(45,1,yMb);_.Xc=function Ve(){OBb(this.b,ge(this.a.a))};ypb(65,7,rMb,wg);_.Dc=function xg(){};ypb(66,28,xMb,zg);_.Lc=function Ag(){return this.b};_.a=null;_.b=null;ypb(384,375,{86:1,89:1},EX);ypb(385,280,{87:1},GX);_.Mf=function HX(a,b){var c,d,e,g,i,j,k;if(!this.b){ui(a,'x-column-layout-ct');this.b=_q(b,kv("<div class='x-column-inner'><\/div>"));_q(this.b,kv("<div class='x-clear'><\/div>"))}aK(this,a,this.b);j=Cr(b,true);k=j.b-(this.a?(jv(),hv==-1&&(hv=pv()),jv(),hv):0);i=k;d=a.kb.b;for(g=0;g<d;++g){c=g<a.kb.b?Xab(pJb(a.kb,g),55):null;e=Xab(Gi(c,xTb),89);!!e&&Zab(e,86)?Xab(e,86):new EX;i-=UJ(c)}for(g=0;g<d;++g){c=g<a.kb.b?Xab(pJb(a.kb,g),55):null;e=Xab(Gi(c,xTb),89);!!e&&Zab(e,86)?Xab(e,86):new EX;Zab(c,53)?hk(Xab(c,53),-1,-1):c.jc&&ss(TJ(c.Zc()),-1,-1,true)}};_.a=false;_.b=null;ypb(682,668,vNb);_.Ug=function lxb(){return this.Bc};_.ye=function mxb(){return new zyb(this)};_.Rg=function nxb(a){return ixb(this,a)};_.r=null;ypb(681,682,{113:1,117:1,134:1,141:1,142:1,143:1,144:1,145:1,148:1,149:1},vxb);_.Ug=function wxb(){return O3(this.Bc)};_.$c=function xxb(){return !bGb(oOb,this.Bc.style[nOb])};_.gd=function yxb(){this.p&&Oxb(this.o,false,true)};_.a=false;_.b=false;_.c=null;_.e=null;_.f=false;_.g=false;_.i=-1;_.j=false;_.k=null;_.n=false;_.p=false;_.q=-1;ypb(683,1,$Mb,Bxb);_.Hf=function Cxb(a){Axb()};ypb(686,211,{},Pxb);_.Pe=function Qxb(){Lxb(this)};_.Qe=function Rxb(){this.d=D3(this.a.Bc,zTb);this.e=D3(this.a.Bc,jSb);this.a.Bc.style[WSb]=oOb;Nxb(this,(1+Math.cos(3.141592653589793))/2)};_.Re=function Sxb(a){Nxb(this,a)};_.a=null;_.b=false;_.c=false;_.d=0;_.e=-1;_.f=null;_.g=null;_.i=false;ypb(695,1,{},zyb);_.Ce=function Ayb(){return this.a};_.De=function Byb(){return yyb(this)};_.Ee=function Cyb(){!!this.b&&ixb(this.c,this.b)};_.b=null;_.c=null;var hbb=aEb(LQb,'HomePresenter',5),ibb=aEb(LQb,'HomeView$1',14),acb=aEb(ATb,'TeamEditorPresenter',65),bcb=aEb(ATb,'TeamEditorView',66),hhb=aEb(BTb,'ColumnLayout',385),olb=aEb(nRb,'SimplePanel',682),glb=aEb(nRb,'PopupPanel',681),flb=aEb(nRb,'PopupPanel$ResizeAnimation',686),blb=aEb(nRb,'PopupPanel$1',683),nlb=aEb(nRb,'SimplePanel$1',695),ghb=aEb(BTb,'ColumnData',384);INb(S1)(5);