function FX(){}
function hyb(){}
function OU(a,b){a.g=b}
function Ud(a,b){a.Dc(b)}
function _d(a,b){a.Dc(b)}
function ac(a){this.b=a}
function Sxb(a){this.Cc=a}
function Cb(a){kb(a,a.b)}
function wg(a,b){ub.call(this,a,b)}
function vyb(a){IA.call(this);this.b=a}
function fzb(a){this.d=a;this.b=!!this.d.s}
function _b(a){!!a.b.n&&Cb(Gbb(a.b.n,10))}
function Od(){return new zg}
function HX(){gK.call(this);this.u=iUb;this.v=true}
function Db(a,b,c){Bb();ub.call(this,a,b);this.b=c;Gbb(this.i,2).Lc(this)}
function ezb(a){if(!a.b||!a.d.s){throw new zMb}a.b=false;return a.c=a.d.s}
function Pxb(a,b){if(a.s){throw new vFb('SimplePanel can only contain one child widget')}Rxb(a,b)}
function Qxb(a,b){if(a.s!=b){return false}try{gi(b,null)}finally{h4(a.ah(),b.$c());a.s=null}return true}
function Rxb(a,b){if(b==a.s){return}!!b&&(Ibb(b.Bc,57)&&Gbb(b.Bc,57).wf(b),ei(b));!!a.s&&Qxb(a,a.s);a.s=b;if(b){dsb(w4(a.Cc),Hi(a.s));gi(b,a)}}
function tyb(a,b){var c,d,e,g,i,j;a.j||(b=1-b);i=0;e=0;g=0;c=0;d=Mbb(b*a.e);j=Mbb(b*a.f);switch(0){case 2:case 0:i=~~(a.e-d)>>1;e=~~(a.f-j)>>1;g=e+j;c=i+d;}Ozb(a.b.Cc,'rect('+i+kUb+g+kUb+c+kUb+e+'px)')}
function byb(){Sxb.call(this,$doc.createElement(COb));this.e=new hyb;this.p=new vyb(this);e4(this.Cc,$doc.createElement(COb));$xb(this,0,0);x4(w4(this.Cc))[dPb]='gwt-PopupPanel';w4(this.Cc)[dPb]='popupContent'}
function ge(a){var b,c;!a.c&&(a.c=(b=new Db((!a.C&&(a.C=new I7),a.C),(!a.d&&(a.d=new Ub(new Og)),a.d),(!a.b&&(a.b=new Nb),c=new wg((!a.C&&(a.C=new I7),a.C),Od(!a.C&&(a.C=new I7))),_d(c,(!a.F&&(a.F=new lBb),a.F)),c)),Ud(b,(!a.F&&(a.F=new lBb),a.F)),b));return a.c}
function zg(){var a,b,c,d;this.c=new byb;new fKb;this.c.k=true;this.c.c=true;this.c.b=true;this.c.g=true;this.b=new RU;hk(this.b,800,-1);OU(this.b,(fV(),eV));bH(this.b,(gn(),dn));d=new FG(new HX);a=Gbb(d.mb,87);a.b=true;d.Nb=1;d.kc&&fs(Qs(Hi(d),mSb),true);c=new EG;b=new gY;fY(b,eV);XF(c,b);Pxb(this.c,this.b)}
function Ub(){var a,b,c,d,e,g;this.c=new FG(new _W);aj(this.c,true);hj(this.c,Ubb.e);d=new eH;d.Ff('Projects');a=new CX((An(),zn));a.b=true;a.g=true;g=new gQ;g.Nb=1;g.kc&&fs(Qs(Hi(g),mSb),true);g.tb=true;g.sb=true;b=new FP('Add',Vwb((Pg(),Ng(),Dg)));qP(b,new ac(this));cQ(g,b,g.lb.c);e=new y0;e.Nb=1;e.kc&&fs(Qs(Hi(e),mSb),true);cQ(g,e,g.lb.c);c=new FP(ATb,Vwb((Rg(),Fg)));cQ(g,c,g.lb.c);yG(d,g,d.lb.c);this.b=new EG;XF(this.b,new VX);aj(this.b,true);wG(this.c,d,a);XF(d,new PX(0));rG(d,(Kn(),Gn));wG(this.c,this.b,new CX(vn))}
var mUb='co.edu.unal.scrum.client.projects.',kUb='px, ';oqb(5,6,{10:1,117:1,156:1},Db);_.Ec=function Eb(){};_.Gc=function Fb(){};_.Hc=function Gb(){};_.Ic=function Hb(){nb(this,new KDb((Kc(),Ec),this))};_.b=null;oqb(11,12,{2:1},Ub);_.Mc=function Vb(){return this.c};_.Kc=function Wb(a,b){if(a===(Bb(),zb)){if(b){WF(this.b);vG(this.b,b)}}};_.b=null;_.c=null;oqb(14,15,cNb,ac);_.Nc=function bc(a){_b(this,Gbb(a,30))};_.b=null;oqb(45,1,gNb);_.Yc=function Ve(){uCb(this.c,ge(this.b.b))};oqb(65,7,_Mb,wg);_.Ec=function xg(){};oqb(66,28,fNb,zg);_.Mc=function Ag(){return this.c};_.b=null;_.c=null;oqb(384,375,{86:1,89:1},FX);oqb(385,280,{87:1},HX);_.Nf=function IX(a,b){var c,d,e,g,i,j,k;if(!this.c){ui(a,'x-column-layout-ct');this.c=_q(b,kv("<div class='x-column-inner'><\/div>"));_q(this.c,kv("<div class='x-clear'><\/div>"))}bK(this,a,this.c);j=Cr(b,true);k=j.c-(this.b?(jv(),hv==-1&&(hv=pv()),jv(),hv):0);i=k;d=a.lb.c;for(g=0;g<d;++g){c=g<a.lb.c?Gbb(ZJb(a.lb,g),55):null;e=Gbb(Gi(c,jUb),89);!!e&&Ibb(e,86)?Gbb(e,86):new FX;i-=VJ(c)}for(g=0;g<d;++g){c=g<a.lb.c?Gbb(ZJb(a.lb,g),55):null;e=Gbb(Gi(c,jUb),89);!!e&&Ibb(e,86)?Gbb(e,86):new FX;Ibb(c,53)?hk(Gbb(c,53),-1,-1):c.kc&&ss(UJ(c.$c()),-1,-1,true)}};_.b=false;_.c=null;oqb(685,671,eOb);_.ah=function Txb(){return this.Cc};_.ze=function Uxb(){return new fzb(this)};_.Zg=function Vxb(a){return Qxb(this,a)};_.s=null;oqb(684,685,{113:1,117:1,134:1,141:1,142:1,143:1,144:1,145:1,148:1,149:1},byb);_.ah=function cyb(){return w4(this.Cc)};_._c=function dyb(){return !JGb(ZOb,this.Cc.style[YOb])};_.hd=function eyb(){this.q&&uyb(this.p,false,true)};_.b=false;_.c=false;_.d=null;_.f=null;_.g=false;_.i=false;_.j=-1;_.k=false;_.n=null;_.o=false;_.q=false;_.r=-1;oqb(686,1,INb,hyb);_.If=function iyb(a){gyb()};oqb(689,211,{},vyb);_.Qe=function wyb(){ryb(this)};_.Re=function xyb(){this.e=l4(this.b.Cc,lUb);this.f=l4(this.b.Cc,XSb);this.b.Cc.style[ITb]=ZOb;tyb(this,(1+Math.cos(3.141592653589793))/2)};_.Se=function yyb(a){tyb(this,a)};_.b=null;_.c=false;_.d=false;_.e=0;_.f=-1;_.g=null;_.i=null;_.j=false;oqb(698,1,{},fzb);_.De=function gzb(){return this.b};_.Ee=function hzb(){return ezb(this)};_.Fe=function izb(){!!this.c&&Qxb(this.d,this.c)};_.c=null;_.d=null;var Sbb=IEb(xRb,'HomePresenter',5),Tbb=IEb(xRb,'HomeView$1',14),Lcb=IEb(mUb,'TeamEditorPresenter',65),Mcb=IEb(mUb,'TeamEditorView',66),Shb=IEb(nUb,'ColumnLayout',385),emb=IEb(_Rb,'SimplePanel',685),Ylb=IEb(_Rb,'PopupPanel',684),Xlb=IEb(_Rb,'PopupPanel$ResizeAnimation',689),Tlb=IEb(_Rb,'PopupPanel$1',686),dmb=IEb(_Rb,'SimplePanel$1',698),Rhb=IEb(nUb,'ColumnData',384);rOb(e2)(5);