function EX(){}
function xxb(){}
function NU(a,b){a.g=b}
function Ud(a,b){a.Dc(b)}
function _d(a,b){a.Dc(b)}
function ac(a){this.b=a}
function gxb(a){this.Cc=a}
function Cb(a){kb(a,a.b)}
function wg(a,b){ub.call(this,a,b)}
function Lxb(a){HA.call(this);this.b=a}
function vyb(a){this.d=a;this.b=!!this.d.s}
function _b(a){!!a.b.n&&Cb(cbb(a.b.n,10))}
function Od(){return new zg}
function GX(){fK.call(this);this.u=hTb;this.v=true}
function Db(a,b,c){Bb();ub.call(this,a,b);this.b=c;cbb(this.i,2).Lc(this)}
function uyb(a){if(!a.b||!a.d.s){throw new NLb}a.b=false;return a.c=a.d.s}
function dxb(a,b){if(a.s){throw new LEb('SimplePanel can only contain one child widget')}fxb(a,b)}
function exb(a,b){if(a.s!=b){return false}try{gi(b,null)}finally{z3(a.Zg(),b.$c());a.s=null}return true}
function fxb(a,b){if(b==a.s){return}!!b&&(ebb(b.Bc,57)&&cbb(b.Bc,57).wf(b),ei(b));!!a.s&&exb(a,a.s);a.s=b;if(b){urb(O3(a.Cc),Hi(a.s));gi(b,a)}}
function Jxb(a,b){var c,d,e,g,i,j;a.j||(b=1-b);i=0;e=0;g=0;c=0;d=ibb(b*a.e);j=ibb(b*a.f);switch(0){case 2:case 0:i=a.e-d>>1;e=a.f-j>>1;g=e+j;c=i+d;}czb(a.b.Cc,'rect('+i+jTb+g+jTb+c+jTb+e+'px)')}
function rxb(){gxb.call(this,$doc.createElement(PNb));this.e=new xxb;this.p=new Lxb(this);w3(this.Cc,$doc.createElement(PNb));oxb(this,0,0);P3(O3(this.Cc))[qOb]='gwt-PopupPanel';O3(this.Cc)[qOb]='popupContent'}
function ge(a){var b,c;!a.c&&(a.c=(b=new Db((!a.C&&(a.C=new W6),a.C),(!a.d&&(a.d=new Ub(new Og)),a.d),(!a.b&&(a.b=new Nb),c=new wg((!a.C&&(a.C=new W6),a.C),Od(!a.C&&(a.C=new W6))),_d(c,(!a.F&&(a.F=new BAb),a.F)),c)),Ud(b,(!a.F&&(a.F=new BAb),a.F)),b));return a.c}
function zg(){var a,b,c,d;this.c=new rxb;new tJb;this.c.k=true;this.c.c=true;this.c.b=true;this.c.g=true;this.b=new QU;hk(this.b,800,-1);NU(this.b,(eV(),dV));aH(this.b,(gn(),dn));d=new EG(new GX);a=cbb(d.mb,87);a.b=true;d.Nb=1;d.kc&&fs(Qs(Hi(d),lRb),true);c=new DG;b=new fY;eY(b,dV);WF(c,b);dxb(this.c,this.b)}
function Ub(){var a,b,c,d,e,g;this.c=new EG(new $W);aj(this.c,true);hj(this.c,qbb.e);d=new dH;d.Ff('Projects');a=new BX((An(),zn));a.b=true;a.g=true;g=new fQ;g.Nb=1;g.kc&&fs(Qs(Hi(g),lRb),true);g.tb=true;g.sb=true;b=new EP('Add',jwb((Pg(),Ng(),Dg)));pP(b,new ac(this));bQ(g,b,g.lb.c);e=new x0;e.Nb=1;e.kc&&fs(Qs(Hi(e),lRb),true);bQ(g,e,g.lb.c);c=new EP(zSb,jwb((Rg(),Fg)));bQ(g,c,g.lb.c);xG(d,g,d.lb.c);this.b=new DG;WF(this.b,new UX);aj(this.b,true);vG(this.c,d,a);WF(d,new OX(0));qG(d,(Kn(),Gn));vG(this.c,this.b,new BX(vn))}
var lTb='co.edu.unal.scrum.client.projects.',jTb='px, ';Fpb(5,6,{10:1,117:1,156:1},Db);_.Ec=function Eb(){};_.Gc=function Fb(){};_.Hc=function Gb(){};_.Ic=function Hb(){nb(this,new $Cb((Kc(),Ec),this))};_.b=null;Fpb(11,12,{2:1},Ub);_.Mc=function Vb(){return this.c};_.Kc=function Wb(a,b){if(a===(Bb(),zb)){if(b){VF(this.b);uG(this.b,b)}}};_.b=null;_.c=null;Fpb(14,15,qMb,ac);_.Nc=function bc(a){_b(this,cbb(a,30))};_.b=null;Fpb(45,1,uMb);_.Yc=function Ve(){KBb(this.c,ge(this.b.b))};Fpb(65,7,nMb,wg);_.Ec=function xg(){};Fpb(66,28,tMb,zg);_.Mc=function Ag(){return this.c};_.b=null;_.c=null;Fpb(384,375,{86:1,89:1},EX);Fpb(385,280,{87:1},GX);_.Nf=function HX(a,b){var c,d,e,g,i,j,k;if(!this.c){ui(a,'x-column-layout-ct');this.c=_q(b,kv("<div class='x-column-inner'><\/div>"));_q(this.c,kv("<div class='x-clear'><\/div>"))}aK(this,a,this.c);j=Cr(b,true);k=j.c-(this.b?(jv(),hv==-1&&(hv=pv()),jv(),hv):0);i=k;d=a.lb.c;for(g=0;g<d;++g){c=g<a.lb.c?cbb(lJb(a.lb,g),55):null;e=cbb(Gi(c,iTb),89);!!e&&ebb(e,86)?cbb(e,86):new EX;i-=UJ(c)}for(g=0;g<d;++g){c=g<a.lb.c?cbb(lJb(a.lb,g),55):null;e=cbb(Gi(c,iTb),89);!!e&&ebb(e,86)?cbb(e,86):new EX;ebb(c,53)?hk(cbb(c,53),-1,-1):c.kc&&ss(TJ(c.$c()),-1,-1,true)}};_.b=false;_.c=null;Fpb(680,666,rNb);_.Zg=function hxb(){return this.Cc};_.ze=function ixb(){return new vyb(this)};_.Wg=function jxb(a){return exb(this,a)};_.s=null;Fpb(679,680,{113:1,117:1,134:1,141:1,142:1,143:1,144:1,145:1,148:1,149:1},rxb);_.Zg=function sxb(){return O3(this.Cc)};_._c=function txb(){return !ZFb(kOb,this.Cc.style[jOb])};_.hd=function uxb(){this.q&&Kxb(this.p,false,true)};_.b=false;_.c=false;_.d=null;_.f=null;_.g=false;_.i=false;_.j=-1;_.k=false;_.n=null;_.o=false;_.q=false;_.r=-1;Fpb(681,1,WMb,xxb);_.If=function yxb(a){wxb()};Fpb(684,211,{},Lxb);_.Qe=function Mxb(){Hxb(this)};_.Re=function Nxb(){this.e=D3(this.b.Cc,kTb);this.f=D3(this.b.Cc,WRb);this.b.Cc.style[HSb]=kOb;Jxb(this,(1+Math.cos(3.141592653589793))/2)};_.Se=function Oxb(a){Jxb(this,a)};_.b=null;_.c=false;_.d=false;_.e=0;_.f=-1;_.g=null;_.i=null;_.j=false;Fpb(693,1,{},vyb);_.De=function wyb(){return this.b};_.Ee=function xyb(){return uyb(this)};_.Fe=function yyb(){!!this.c&&exb(this.d,this.c)};_.c=null;_.d=null;var obb=YDb(wQb,'HomePresenter',5),pbb=YDb(wQb,'HomeView$1',14),hcb=YDb(lTb,'TeamEditorPresenter',65),icb=YDb(lTb,'TeamEditorView',66),ohb=YDb(mTb,'ColumnLayout',385),vlb=YDb($Qb,'SimplePanel',680),nlb=YDb($Qb,'PopupPanel',679),mlb=YDb($Qb,'PopupPanel$ResizeAnimation',684),ilb=YDb($Qb,'PopupPanel$1',681),ulb=YDb($Qb,'SimplePanel$1',693),nhb=YDb(mTb,'ColumnData',384);ENb(S1)(5);