function JX(){}
function $yb(){}
function SU(a,b){a.f=b}
function Vd(a,b){a.Cc(b)}
function ae(a,b){a.Cc(b)}
function bc(a){this.a=a}
function Jyb(a){this.Bc=a}
function Db(a){lb(a,a.a)}
function Pd(){return new Ag}
function xg(a,b){vb.call(this,a,b)}
function mzb(a){MA.call(this);this.a=a}
function Yzb(a){this.c=a;this.a=!!this.c.r}
function LX(){kK.call(this);this.t=S9b;this.u=true}
function ac(a){!!a.a.k&&Db(Gbb(a.a.k,10))}
function Gyb(a,b){if(a.r){throw new yGb(X9b)}Iyb(a,b)}
function Xzb(a){if(!a.a||!a.c.r){throw new BNb}a.a=false;return a.b=a.c.r}
function Eb(a,b,c){Cb();vb.call(this,a,b);this.a=c;Gbb(this.g,2).Kc(this)}
function Hyb(a,b){if(a.r!=b){return false}try{ji(b,null)}finally{E3(a.eh(),b.Zc());a.r=null}return true}
function Iyb(a,b){if(b==a.r){return}!!b&&(Ibb(b.Ac,57)&&Gbb(b.Ac,57).wf(b),hi(b));!!a.r&&Hyb(a,a.r);a.r=b;if(b){Isb(T3(a.Bc),Ki(a.r));ji(b,a)}}
function Uyb(){Jyb.call(this,W3($doc,JPb));this.d=new $yb;this.o=new mzb(this);B3(this.Bc,W3($doc,JPb));Ryb(this,0,0);U3(T3(this.Bc))[ZQb]=Y9b;T3(this.Bc)[ZQb]=Z9b}
function kzb(a,b){var c,d,e,g,i,j;a.i||(b=1-b);i=0;e=0;g=0;c=0;d=Mbb(b*a.d);j=Mbb(b*a.e);switch(0){case 2:case 0:i=a.d-d>>1;e=a.e-j>>1;g=e+j;c=i+d;}OAb(a.a.Bc,$9b+i+_9b+g+_9b+c+_9b+e+aac)}
function he(a){var b,c;!a.b&&(a.b=(b=new Eb((!a.B&&(a.B=new y7),a.B),(!a.c&&(a.c=new Vb(new Rg)),a.c),(!a.a&&(a.a=new Ob),c=new xg((!a.B&&(a.B=new y7),a.B),Pd(!a.B&&(a.B=new y7))),ae(c,(!a.E&&(a.E=new oCb),a.E)),c)),Vd(b,(!a.E&&(a.E=new oCb),a.E)),b));return a.b}
function Ag(){var a,b,c,d;this.b=new Uyb;new hLb;this.b.j=true;this.b.b=true;this.b.a=true;this.b.f=true;this.a=new VU;kk(this.a,800,-1);SU(this.a,(jV(),iV));fH(this.a,(ln(),hn));d=new JG(new LX);a=Gbb(d.lb,87);a.a=true;d.Mb=1;d.jc&&js(Us(Ki(d),Z2b),true);c=new IG;b=new kY;jY(b,iV);_F(c,b);Gyb(this.b,this.a)}
function Vb(){var a,b,c,d,e,g;this.b=new JG(new dX);dj(this.b,true);kj(this.b,Ubb.d);d=new iH;d.Ff(Q9b);a=new GX((En(),Dn));a.a=true;a.f=true;g=new kQ;g.Mb=1;g.jc&&js(Us(Ki(g),Z2b),true);g.sb=true;g.rb=true;b=new JP(R9b,Mxb((Sg(),Qg(),Gg)));uP(b,new bc(this));gQ(g,b,g.kb.b);e=new C0;e.Mb=1;e.jc&&js(Us(Ki(e),Z2b),true);gQ(g,e,g.kb.b);c=new JP(h7b,Mxb((Ug(),Ig)));gQ(g,c,g.kb.b);CG(d,g,d.kb.b);this.a=new IG;_F(this.a,new ZX);dj(this.a,true);AG(this.b,d,a);_F(d,new TX(0));vG(d,(On(),Kn));AG(this.b,this.a,new GX(zn))}
var V9b="<div class='x-clear'><\/div>",U9b="<div class='x-column-inner'><\/div>",R9b='Add',oac='ColumnData',iac='ColumnLayout',cac='HomePresenter',dac='HomeView$1',kac='PopupPanel',mac='PopupPanel$1',lac='PopupPanel$ResizeAnimation',Q9b='Projects',jac='SimplePanel',X9b='SimplePanel can only contain one child widget',nac='SimplePanel$1',fac='TeamEditorPresenter',gac='TeamEditorView',eac='co.edu.unal.scrum.client.projects.',Y9b='gwt-PopupPanel',Z9b='popupContent',aac='px)',_9b='px, ',$9b='rect(',T9b='x-column-layout-ct';qqb(5,6,{10:1,117:1,157:1},Eb);_.Dc=function Fb(){};_.Fc=function Gb(){};_.Gc=function Hb(){};_.Hc=function Ib(){ob(this,new NEb((Lc(),Fc),this))};_.a=null;qqb(11,12,{2:1},Vb);_.Lc=function Wb(){return this.b};_.Jc=function Xb(a,b){if(a===(Cb(),Ab)){if(b){$F(this.a);zG(this.a,b)}}};_.a=null;_.b=null;qqb(14,15,eOb,bc);_.Mc=function cc(a){ac(this,Gbb(a,30))};_.a=null;qqb(45,1,iOb);_.Xc=function We(){xDb(this.b,he(this.a.a))};qqb(65,7,bOb,xg);_.Dc=function yg(){};qqb(66,28,hOb,Ag);_.Lc=function Bg(){return this.b};_.a=null;_.b=null;qqb(385,376,{86:1,89:1},JX);qqb(386,281,{87:1},LX);_.Nf=function MX(a,b){var c,d,e,g,i,j,k;if(!this.b){xi(a,T9b);this.b=dr(b,ov(U9b));dr(this.b,ov(V9b))}fK(this,a,this.b);j=Gr(b,true);k=j.b-(this.a?(nv(),lv==-1&&(lv=tv()),nv(),lv):0);i=k;d=a.kb.b;for(g=0;g<d;++g){c=g<a.kb.b?Gbb(_Kb(a.kb,g),55):null;e=Gbb(Ji(c,W9b),89);!!e&&Ibb(e,86)?Gbb(e,86):new JX;i-=ZJ(c)}for(g=0;g<d;++g){c=g<a.kb.b?Gbb(_Kb(a.kb,g),55):null;e=Gbb(Ji(c,W9b),89);!!e&&Ibb(e,86)?Gbb(e,86):new JX;Ibb(c,53)?kk(Gbb(c,53),-1,-1):c.jc&&ws(YJ(c.Zc()),-1,-1,true)}};_.a=false;_.b=null;qqb(688,674,fPb);_.eh=function Kyb(){return this.Bc};_.ze=function Lyb(){return new Yzb(this)};_.bh=function Myb(a){return Hyb(this,a)};_.r=null;qqb(687,688,{113:1,117:1,135:1,142:1,143:1,144:1,145:1,146:1,149:1,150:1},Uyb);_.eh=function Vyb(){return T3(this.Bc)};_.$c=function Wyb(){return !NHb(TQb,this.Bc.style[SQb])};_.gd=function Xyb(){this.p&&lzb(this.o,false,true)};_.a=false;_.b=false;_.c=null;_.e=null;_.f=false;_.g=false;_.i=-1;_.j=false;_.k=null;_.n=false;_.p=false;_.q=-1;qqb(689,1,KOb,$yb);_.If=function _yb(a){Zyb()};qqb(692,212,{},mzb);_.Qe=function nzb(){izb(this)};_.Re=function ozb(){this.d=I3(this.a.Bc,bac);this.e=I3(this.a.Bc,v4b);this.a.Bc.style[N7b]=TQb;kzb(this,(1+Math.cos(3.141592653589793))/2)};_.Se=function pzb(a){kzb(this,a)};_.a=null;_.b=false;_.c=false;_.d=0;_.e=-1;_.f=null;_.g=null;_.i=false;qqb(701,1,{},Yzb);_.De=function Zzb(){return this.a};_.Ee=function $zb(){return Xzb(this)};_.Fe=function _zb(){!!this.b&&Hyb(this.c,this.b)};_.b=null;_.c=null;var Sbb=LFb(NYb,cac,5),Tbb=LFb(NYb,dac,14),Lcb=LFb(eac,fac,65),Mcb=LFb(eac,gac,66),Thb=LFb(hac,iac,386),dmb=LFb(y1b,jac,688),Xlb=LFb(y1b,kac,687),Wlb=LFb(y1b,lac,692),Slb=LFb(y1b,mac,689),cmb=LFb(y1b,nac,701),Shb=LFb(hac,oac,385);sPb(X1)(5);