function FX(){}
function ryb(){}
function OU(a,b){a.g=b}
function Ud(a,b){a.Dc(b)}
function _d(a,b){a.Dc(b)}
function ac(a){this.b=a}
function ayb(a){this.Cc=a}
function Cb(a){kb(a,a.b)}
function wg(a,b){ub.call(this,a,b)}
function Fyb(a){IA.call(this);this.b=a}
function pzb(a){this.d=a;this.b=!!this.d.s}
function _b(a){!!a.b.n&&Cb(Qbb(a.b.n,10))}
function Od(){return new zg}
function HX(){gK.call(this);this.u=hUb;this.v=true}
function Db(a,b,c){Bb();ub.call(this,a,b);this.b=c;Qbb(this.i,2).Lc(this)}
function ozb(a){if(!a.b||!a.d.s){throw new JMb}a.b=false;return a.c=a.d.s}
function Zxb(a,b){if(a.s){throw new FFb('SimplePanel can only contain one child widget')}_xb(a,b)}
function $xb(a,b){if(a.s!=b){return false}try{gi(b,null)}finally{h4(a.fh(),b.$c());a.s=null}return true}
function _xb(a,b){if(b==a.s){return}!!b&&(Sbb(b.Bc,57)&&Qbb(b.Bc,57).wf(b),ei(b));!!a.s&&$xb(a,a.s);a.s=b;if(b){nsb(w4(a.Cc),Hi(a.s));gi(b,a)}}
function Dyb(a,b){var c,d,e,g,i,j;a.j||(b=1-b);i=0;e=0;g=0;c=0;d=Wbb(b*a.e);j=Wbb(b*a.f);switch(0){case 2:case 0:i=~~(a.e-d)>>1;e=~~(a.f-j)>>1;g=e+j;c=i+d;}Yzb(a.b.Cc,'rect('+i+jUb+g+jUb+c+jUb+e+'px)')}
function lyb(){ayb.call(this,$doc.createElement(MOb));this.e=new ryb;this.p=new Fyb(this);e4(this.Cc,$doc.createElement(MOb));iyb(this,0,0);x4(w4(this.Cc))[nPb]='gwt-PopupPanel';w4(this.Cc)[nPb]='popupContent'}
function ge(a){var b,c;!a.c&&(a.c=(b=new Db((!a.C&&(a.C=new I7),a.C),(!a.d&&(a.d=new Ub(new Og)),a.d),(!a.b&&(a.b=new Nb),c=new wg((!a.C&&(a.C=new I7),a.C),Od(!a.C&&(a.C=new I7))),_d(c,(!a.F&&(a.F=new vBb),a.F)),c)),Ud(b,(!a.F&&(a.F=new vBb),a.F)),b));return a.c}
function zg(){var a,b,c,d;this.c=new lyb;new pKb;this.c.k=true;this.c.c=true;this.c.b=true;this.c.g=true;this.b=new RU;hk(this.b,800,-1);OU(this.b,(fV(),eV));bH(this.b,(gn(),dn));d=new FG(new HX);a=Qbb(d.mb,87);a.b=true;d.Nb=1;d.kc&&fs(Qs(Hi(d),lSb),true);c=new EG;b=new gY;fY(b,eV);XF(c,b);Zxb(this.c,this.b)}
function Ub(){var a,b,c,d,e,g;this.c=new FG(new _W);aj(this.c,true);hj(this.c,ccb.e);d=new eH;d.Ff('Projects');a=new CX((An(),zn));a.b=true;a.g=true;g=new gQ;g.Nb=1;g.kc&&fs(Qs(Hi(g),lSb),true);g.tb=true;g.sb=true;b=new FP('Add',dxb((Pg(),Ng(),Dg)));qP(b,new ac(this));cQ(g,b,g.lb.c);e=new y0;e.Nb=1;e.kc&&fs(Qs(Hi(e),lSb),true);cQ(g,e,g.lb.c);c=new FP(zTb,dxb((Rg(),Fg)));cQ(g,c,g.lb.c);yG(d,g,d.lb.c);this.b=new EG;XF(this.b,new VX);aj(this.b,true);wG(this.c,d,a);XF(d,new PX(0));rG(d,(Kn(),Gn));wG(this.c,this.b,new CX(vn))}
var lUb='co.edu.unal.scrum.client.projects.',jUb='px, ';yqb(5,6,{10:1,117:1,156:1},Db);_.Ec=function Eb(){};_.Gc=function Fb(){};_.Hc=function Gb(){};_.Ic=function Hb(){nb(this,new UDb((Kc(),Ec),this))};_.b=null;yqb(11,12,{2:1},Ub);_.Mc=function Vb(){return this.c};_.Kc=function Wb(a,b){if(a===(Bb(),zb)){if(b){WF(this.b);vG(this.b,b)}}};_.b=null;_.c=null;yqb(14,15,mNb,ac);_.Nc=function bc(a){_b(this,Qbb(a,30))};_.b=null;yqb(45,1,qNb);_.Yc=function Ve(){ECb(this.c,ge(this.b.b))};yqb(65,7,jNb,wg);_.Ec=function xg(){};yqb(66,28,pNb,zg);_.Mc=function Ag(){return this.c};_.b=null;_.c=null;yqb(384,375,{86:1,89:1},FX);yqb(385,280,{87:1},HX);_.Nf=function IX(a,b){var c,d,e,g,i,j,k;if(!this.c){ui(a,'x-column-layout-ct');this.c=_q(b,kv("<div class='x-column-inner'><\/div>"));_q(this.c,kv("<div class='x-clear'><\/div>"))}bK(this,a,this.c);j=Cr(b,true);k=j.c-(this.b?(jv(),hv==-1&&(hv=pv()),jv(),hv):0);i=k;d=a.lb.c;for(g=0;g<d;++g){c=g<a.lb.c?Qbb(hKb(a.lb,g),55):null;e=Qbb(Gi(c,iUb),89);!!e&&Sbb(e,86)?Qbb(e,86):new FX;i-=VJ(c)}for(g=0;g<d;++g){c=g<a.lb.c?Qbb(hKb(a.lb,g),55):null;e=Qbb(Gi(c,iUb),89);!!e&&Sbb(e,86)?Qbb(e,86):new FX;Sbb(c,53)?hk(Qbb(c,53),-1,-1):c.kc&&ss(UJ(c.$c()),-1,-1,true)}};_.b=false;_.c=null;yqb(685,671,oOb);_.fh=function byb(){return this.Cc};_.ze=function cyb(){return new pzb(this)};_.ch=function dyb(a){return $xb(this,a)};_.s=null;yqb(684,685,{113:1,117:1,134:1,141:1,142:1,143:1,144:1,145:1,148:1,149:1},lyb);_.fh=function myb(){return w4(this.Cc)};_._c=function nyb(){return !TGb(hPb,this.Cc.style[gPb])};_.hd=function oyb(){this.q&&Eyb(this.p,false,true)};_.b=false;_.c=false;_.d=null;_.f=null;_.g=false;_.i=false;_.j=-1;_.k=false;_.n=null;_.o=false;_.q=false;_.r=-1;yqb(686,1,SNb,ryb);_.If=function syb(a){qyb()};yqb(689,211,{},Fyb);_.Qe=function Gyb(){Byb(this)};_.Re=function Hyb(){this.e=l4(this.b.Cc,kUb);this.f=l4(this.b.Cc,WSb);this.b.Cc.style[HTb]=hPb;Dyb(this,(1+Math.cos(3.141592653589793))/2)};_.Se=function Iyb(a){Dyb(this,a)};_.b=null;_.c=false;_.d=false;_.e=0;_.f=-1;_.g=null;_.i=null;_.j=false;yqb(698,1,{},pzb);_.De=function qzb(){return this.b};_.Ee=function rzb(){return ozb(this)};_.Fe=function szb(){!!this.c&&$xb(this.d,this.c)};_.c=null;_.d=null;var acb=SEb(wRb,'HomePresenter',5),bcb=SEb(wRb,'HomeView$1',14),Vcb=SEb(lUb,'TeamEditorPresenter',65),Wcb=SEb(lUb,'TeamEditorView',66),aib=SEb(mUb,'ColumnLayout',385),omb=SEb($Rb,'SimplePanel',685),gmb=SEb($Rb,'PopupPanel',684),fmb=SEb($Rb,'PopupPanel$ResizeAnimation',689),bmb=SEb($Rb,'PopupPanel$1',686),nmb=SEb($Rb,'SimplePanel$1',698),_hb=SEb(mUb,'ColumnData',384);BOb(e2)(5);