function EX(){}
function Dxb(){}
function NU(a,b){a.f=b}
function Ud(a,b){a.Cc(b)}
function _d(a,b){a.Cc(b)}
function ac(a){this.a=a}
function mxb(a){this.Bc=a}
function Cb(a){kb(a,a.a)}
function Od(){return new zg}
function wg(a,b){ub.call(this,a,b)}
function Rxb(a){HA.call(this);this.a=a}
function Byb(a){this.c=a;this.a=!!this.c.r}
function GX(){fK.call(this);this.t=yTb;this.u=true}
function _b(a){!!a.a.k&&Cb(Yab(a.a.k,10))}
function Db(a,b,c){Bb();ub.call(this,a,b);this.a=c;Yab(this.g,2).Kc(this)}
function Ayb(a){if(!a.a||!a.c.r){throw new TLb}a.a=false;return a.b=a.c.r}
function jxb(a,b){if(a.r){throw new REb('SimplePanel can only contain one child widget')}lxb(a,b)}
function kxb(a,b){if(a.r!=b){return false}try{gi(b,null)}finally{z3(a.Ug(),b.Zc());a.r=null}return true}
function lxb(a,b){if(b==a.r){return}!!b&&($ab(b.Ac,57)&&Yab(b.Ac,57).vf(b),ei(b));!!a.r&&kxb(a,a.r);a.r=b;if(b){urb(O3(a.Bc),Hi(a.r));gi(b,a)}}
function Pxb(a,b){var c,d,e,g,i,j;a.i||(b=1-b);i=0;e=0;g=0;c=0;d=cbb(b*a.d);j=cbb(b*a.e);switch(0){case 2:case 0:i=a.d-d>>1;e=a.e-j>>1;g=e+j;c=i+d;}izb(a.a.Bc,'rect('+i+ATb+g+ATb+c+ATb+e+'px)')}
function xxb(){mxb.call(this,$doc.createElement(VNb));this.d=new Dxb;this.o=new Rxb(this);w3(this.Bc,$doc.createElement(VNb));uxb(this,0,0);P3(O3(this.Bc))[wOb]='gwt-PopupPanel';O3(this.Bc)[wOb]='popupContent'}
function ge(a){var b,c;!a.b&&(a.b=(b=new Db((!a.B&&(a.B=new $6),a.B),(!a.c&&(a.c=new Ub(new Og)),a.c),(!a.a&&(a.a=new Nb),c=new wg((!a.B&&(a.B=new $6),a.B),Od(!a.B&&(a.B=new $6))),_d(c,(!a.E&&(a.E=new HAb),a.E)),c)),Ud(b,(!a.E&&(a.E=new HAb),a.E)),b));return a.b}
function zg(){var a,b,c,d;this.b=new xxb;new zJb;this.b.j=true;this.b.b=true;this.b.a=true;this.b.f=true;this.a=new QU;hk(this.a,800,-1);NU(this.a,(eV(),dV));aH(this.a,(gn(),dn));d=new EG(new GX);a=Yab(d.lb,87);a.a=true;d.Mb=1;d.jc&&fs(Qs(Hi(d),CRb),true);c=new DG;b=new fY;eY(b,dV);WF(c,b);jxb(this.b,this.a)}
function Ub(){var a,b,c,d,e,g;this.b=new EG(new $W);aj(this.b,true);hj(this.b,kbb.d);d=new dH;d.Ef('Projects');a=new BX((An(),zn));a.a=true;a.f=true;g=new fQ;g.Mb=1;g.jc&&fs(Qs(Hi(g),CRb),true);g.sb=true;g.rb=true;b=new EP('Add',pwb((Pg(),Ng(),Dg)));pP(b,new ac(this));bQ(g,b,g.kb.b);e=new x0;e.Mb=1;e.jc&&fs(Qs(Hi(e),CRb),true);bQ(g,e,g.kb.b);c=new EP(QSb,pwb((Rg(),Fg)));bQ(g,c,g.kb.b);xG(d,g,d.kb.b);this.a=new DG;WF(this.a,new UX);aj(this.a,true);vG(this.b,d,a);WF(d,new OX(0));qG(d,(Kn(),Gn));vG(this.b,this.a,new BX(vn))}
var CTb='co.edu.unal.scrum.client.projects.',ATb='px, ';Apb(5,6,{10:1,117:1,156:1},Db);_.Dc=function Eb(){};_.Fc=function Fb(){};_.Gc=function Gb(){};_.Hc=function Hb(){nb(this,new eDb((Kc(),Ec),this))};_.a=null;Apb(11,12,{2:1},Ub);_.Lc=function Vb(){return this.b};_.Jc=function Wb(a,b){if(a===(Bb(),zb)){if(b){VF(this.a);uG(this.a,b)}}};_.a=null;_.b=null;Apb(14,15,wMb,ac);_.Mc=function bc(a){_b(this,Yab(a,30))};_.a=null;Apb(45,1,AMb);_.Xc=function Ve(){QBb(this.b,ge(this.a.a))};Apb(65,7,tMb,wg);_.Dc=function xg(){};Apb(66,28,zMb,zg);_.Lc=function Ag(){return this.b};_.a=null;_.b=null;Apb(384,375,{86:1,89:1},EX);Apb(385,280,{87:1},GX);_.Mf=function HX(a,b){var c,d,e,g,i,j,k;if(!this.b){ui(a,'x-column-layout-ct');this.b=_q(b,kv("<div class='x-column-inner'><\/div>"));_q(this.b,kv("<div class='x-clear'><\/div>"))}aK(this,a,this.b);j=Cr(b,true);k=j.b-(this.a?(jv(),hv==-1&&(hv=pv()),jv(),hv):0);i=k;d=a.kb.b;for(g=0;g<d;++g){c=g<a.kb.b?Yab(rJb(a.kb,g),55):null;e=Yab(Gi(c,zTb),89);!!e&&$ab(e,86)?Yab(e,86):new EX;i-=UJ(c)}for(g=0;g<d;++g){c=g<a.kb.b?Yab(rJb(a.kb,g),55):null;e=Yab(Gi(c,zTb),89);!!e&&$ab(e,86)?Yab(e,86):new EX;$ab(c,53)?hk(Yab(c,53),-1,-1):c.jc&&ss(TJ(c.Zc()),-1,-1,true)}};_.a=false;_.b=null;Apb(684,670,xNb);_.Ug=function nxb(){return this.Bc};_.ye=function oxb(){return new Byb(this)};_.Rg=function pxb(a){return kxb(this,a)};_.r=null;Apb(683,684,{113:1,117:1,134:1,141:1,142:1,143:1,144:1,145:1,148:1,149:1},xxb);_.Ug=function yxb(){return O3(this.Bc)};_.$c=function zxb(){return !dGb(qOb,this.Bc.style[pOb])};_.gd=function Axb(){this.p&&Qxb(this.o,false,true)};_.a=false;_.b=false;_.c=null;_.e=null;_.f=false;_.g=false;_.i=-1;_.j=false;_.k=null;_.n=false;_.p=false;_.q=-1;Apb(685,1,aNb,Dxb);_.Hf=function Exb(a){Cxb()};Apb(688,211,{},Rxb);_.Pe=function Sxb(){Nxb(this)};_.Qe=function Txb(){this.d=D3(this.a.Bc,BTb);this.e=D3(this.a.Bc,lSb);this.a.Bc.style[YSb]=qOb;Pxb(this,(1+Math.cos(3.141592653589793))/2)};_.Re=function Uxb(a){Pxb(this,a)};_.a=null;_.b=false;_.c=false;_.d=0;_.e=-1;_.f=null;_.g=null;_.i=false;Apb(697,1,{},Byb);_.Ce=function Cyb(){return this.a};_.De=function Dyb(){return Ayb(this)};_.Ee=function Eyb(){!!this.b&&kxb(this.c,this.b)};_.b=null;_.c=null;var ibb=cEb(NQb,'HomePresenter',5),jbb=cEb(NQb,'HomeView$1',14),bcb=cEb(CTb,'TeamEditorPresenter',65),ccb=cEb(CTb,'TeamEditorView',66),ihb=cEb(DTb,'ColumnLayout',385),qlb=cEb(pRb,'SimplePanel',684),ilb=cEb(pRb,'PopupPanel',683),hlb=cEb(pRb,'PopupPanel$ResizeAnimation',688),dlb=cEb(pRb,'PopupPanel$1',685),plb=cEb(pRb,'SimplePanel$1',697),hhb=cEb(DTb,'ColumnData',384);KNb(S1)(5);