function FX(){}
function Gxb(){}
function OU(a,b){a.f=b}
function Ud(a,b){a.Cc(b)}
function _d(a,b){a.Cc(b)}
function ac(a){this.a=a}
function pxb(a){this.Bc=a}
function Cb(a){kb(a,a.a)}
function Od(){return new zg}
function wg(a,b){ub.call(this,a,b)}
function Uxb(a){IA.call(this);this.a=a}
function Eyb(a){this.c=a;this.a=!!this.c.r}
function HX(){gK.call(this);this.t=GTb;this.u=true}
function _b(a){!!a.a.k&&Cb(dbb(a.a.k,10))}
function Db(a,b,c){Bb();ub.call(this,a,b);this.a=c;dbb(this.g,2).Kc(this)}
function Dyb(a){if(!a.a||!a.c.r){throw new WLb}a.a=false;return a.b=a.c.r}
function mxb(a,b){if(a.r){throw new UEb('SimplePanel can only contain one child widget')}oxb(a,b)}
function nxb(a,b){if(a.r!=b){return false}try{gi(b,null)}finally{A3(a.Ug(),b.Zc());a.r=null}return true}
function oxb(a,b){if(b==a.r){return}!!b&&(fbb(b.Ac,57)&&dbb(b.Ac,57).vf(b),ei(b));!!a.r&&nxb(a,a.r);a.r=b;if(b){Brb(P3(a.Bc),Hi(a.r));gi(b,a)}}
function Axb(){pxb.call(this,S3($doc,YNb));this.d=new Gxb;this.o=new Uxb(this);x3(this.Bc,S3($doc,YNb));xxb(this,0,0);Q3(P3(this.Bc))[zOb]='gwt-PopupPanel';P3(this.Bc)[zOb]='popupContent'}
function Sxb(a,b){var c,d,e,g,i,j;a.i||(b=1-b);i=0;e=0;g=0;c=0;d=jbb(b*a.d);j=jbb(b*a.e);switch(0){case 2:case 0:i=a.d-d>>1;e=a.e-j>>1;g=e+j;c=i+d;}lzb(a.a.Bc,'rect('+i+ITb+g+ITb+c+ITb+e+'px)')}
function ge(a){var b,c;!a.b&&(a.b=(b=new Db((!a.B&&(a.B=new g7),a.B),(!a.c&&(a.c=new Ub(new Og)),a.c),(!a.a&&(a.a=new Nb),c=new wg((!a.B&&(a.B=new g7),a.B),Od(!a.B&&(a.B=new g7))),_d(c,(!a.E&&(a.E=new KAb),a.E)),c)),Ud(b,(!a.E&&(a.E=new KAb),a.E)),b));return a.b}
function zg(){var a,b,c,d;this.b=new Axb;new CJb;this.b.j=true;this.b.b=true;this.b.a=true;this.b.f=true;this.a=new RU;hk(this.a,800,-1);OU(this.a,(fV(),eV));bH(this.a,(gn(),dn));d=new FG(new HX);a=dbb(d.lb,87);a.a=true;d.Mb=1;d.jc&&fs(Qs(Hi(d),KRb),true);c=new EG;b=new gY;fY(b,eV);XF(c,b);mxb(this.b,this.a)}
function Ub(){var a,b,c,d,e,g;this.b=new FG(new _W);aj(this.b,true);hj(this.b,rbb.d);d=new eH;d.Ef('Projects');a=new CX((An(),zn));a.a=true;a.f=true;g=new gQ;g.Mb=1;g.jc&&fs(Qs(Hi(g),KRb),true);g.sb=true;g.rb=true;b=new FP('Add',swb((Pg(),Ng(),Dg)));qP(b,new ac(this));cQ(g,b,g.kb.b);e=new y0;e.Mb=1;e.jc&&fs(Qs(Hi(e),KRb),true);cQ(g,e,g.kb.b);c=new FP(YSb,swb((Rg(),Fg)));cQ(g,c,g.kb.b);yG(d,g,d.kb.b);this.a=new EG;XF(this.a,new VX);aj(this.a,true);wG(this.b,d,a);XF(d,new PX(0));rG(d,(Kn(),Gn));wG(this.b,this.a,new CX(vn))}
var KTb='co.edu.unal.scrum.client.projects.',ITb='px, ';Hpb(5,6,{10:1,117:1,156:1},Db);_.Dc=function Eb(){};_.Fc=function Fb(){};_.Gc=function Gb(){};_.Hc=function Hb(){nb(this,new hDb((Kc(),Ec),this))};_.a=null;Hpb(11,12,{2:1},Ub);_.Lc=function Vb(){return this.b};_.Jc=function Wb(a,b){if(a===(Bb(),zb)){if(b){WF(this.a);vG(this.a,b)}}};_.a=null;_.b=null;Hpb(14,15,zMb,ac);_.Mc=function bc(a){_b(this,dbb(a,30))};_.a=null;Hpb(45,1,DMb);_.Xc=function Ve(){TBb(this.b,ge(this.a.a))};Hpb(65,7,wMb,wg);_.Dc=function xg(){};Hpb(66,28,CMb,zg);_.Lc=function Ag(){return this.b};_.a=null;_.b=null;Hpb(385,376,{86:1,89:1},FX);Hpb(386,281,{87:1},HX);_.Mf=function IX(a,b){var c,d,e,g,i,j,k;if(!this.b){ui(a,'x-column-layout-ct');this.b=_q(b,kv("<div class='x-column-inner'><\/div>"));_q(this.b,kv("<div class='x-clear'><\/div>"))}bK(this,a,this.b);j=Cr(b,true);k=j.b-(this.a?(jv(),hv==-1&&(hv=pv()),jv(),hv):0);i=k;d=a.kb.b;for(g=0;g<d;++g){c=g<a.kb.b?dbb(uJb(a.kb,g),55):null;e=dbb(Gi(c,HTb),89);!!e&&fbb(e,86)?dbb(e,86):new FX;i-=VJ(c)}for(g=0;g<d;++g){c=g<a.kb.b?dbb(uJb(a.kb,g),55):null;e=dbb(Gi(c,HTb),89);!!e&&fbb(e,86)?dbb(e,86):new FX;fbb(c,53)?hk(dbb(c,53),-1,-1):c.jc&&ss(UJ(c.Zc()),-1,-1,true)}};_.a=false;_.b=null;Hpb(680,666,ANb);_.Ug=function qxb(){return this.Bc};_.ye=function rxb(){return new Eyb(this)};_.Rg=function sxb(a){return nxb(this,a)};_.r=null;Hpb(679,680,{113:1,117:1,134:1,141:1,142:1,143:1,144:1,145:1,148:1,149:1},Axb);_.Ug=function Bxb(){return P3(this.Bc)};_.$c=function Cxb(){return !gGb(tOb,this.Bc.style[sOb])};_.gd=function Dxb(){this.p&&Txb(this.o,false,true)};_.a=false;_.b=false;_.c=null;_.e=null;_.f=false;_.g=false;_.i=-1;_.j=false;_.k=null;_.n=false;_.p=false;_.q=-1;Hpb(681,1,dNb,Gxb);_.Hf=function Hxb(a){Fxb()};Hpb(684,212,{},Uxb);_.Pe=function Vxb(){Qxb(this)};_.Qe=function Wxb(){this.d=E3(this.a.Bc,JTb);this.e=E3(this.a.Bc,tSb);this.a.Bc.style[fTb]=tOb;Sxb(this,(1+Math.cos(3.141592653589793))/2)};_.Re=function Xxb(a){Sxb(this,a)};_.a=null;_.b=false;_.c=false;_.d=0;_.e=-1;_.f=null;_.g=null;_.i=false;Hpb(693,1,{},Eyb);_.Ce=function Fyb(){return this.a};_.De=function Gyb(){return Dyb(this)};_.Ee=function Hyb(){!!this.b&&nxb(this.c,this.b)};_.b=null;_.c=null;var pbb=fEb(UQb,'HomePresenter',5),qbb=fEb(UQb,'HomeView$1',14),icb=fEb(KTb,'TeamEditorPresenter',65),jcb=fEb(KTb,'TeamEditorView',66),qhb=fEb(LTb,'ColumnLayout',386),xlb=fEb(wRb,'SimplePanel',680),plb=fEb(wRb,'PopupPanel',679),olb=fEb(wRb,'PopupPanel$ResizeAnimation',684),klb=fEb(wRb,'PopupPanel$1',681),wlb=fEb(wRb,'SimplePanel$1',693),phb=fEb(LTb,'ColumnData',385);NNb(T1)(5);