// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package co.edu.unal.scrum.shared.model;

import java.util.Date;

public class ProjectBuilder extends ProjectBuilderBase<ProjectBuilder> {
	public static ProjectBuilder project() {
		return new ProjectBuilder();
	}

	public ProjectBuilder() {
		super(new Project());
	}

	public Project build() {
		return getInstance();
	}
}

class ProjectBuilderBase<GeneratorT extends ProjectBuilderBase<GeneratorT>> {
	private Project instance;

	protected ProjectBuilderBase(Project aInstance) {
		instance = aInstance;
	}

	protected Project getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withDateEnd(Date aValue) {
		instance.setDateEnd(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withDateStart(Date aValue) {
		instance.setDateStart(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withName(String aValue) {
		instance.setName(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withStatus(String aValue) {
		instance.setStatus(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withIdProject(long aValue) {
		instance.setIdProject(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withDescription(String aValue) {
		instance.setDescription(aValue);

		return (GeneratorT) this;
	}
}
