function EX(){}
function lxb(){}
function NU(a,b){a.g=b}
function Ud(a,b){a.Dc(b)}
function _d(a,b){a.Dc(b)}
function ac(a){this.b=a}
function Wwb(a){this.Cc=a}
function Cb(a){kb(a,a.b)}
function wg(a,b){ub.call(this,a,b)}
function zxb(a){HA.call(this);this.b=a}
function jyb(a){this.d=a;this.b=!!this.d.s}
function _b(a){!!a.b.n&&Cb(Tab(a.b.n,10))}
function Od(){return new zg}
function GX(){fK.call(this);this.u=gTb;this.v=true}
function Db(a,b,c){Bb();ub.call(this,a,b);this.b=c;Tab(this.i,2).Lc(this)}
function iyb(a){if(!a.b||!a.d.s){throw new BLb}a.b=false;return a.c=a.d.s}
function Twb(a,b){if(a.s){throw new zEb('SimplePanel can only contain one child widget')}Vwb(a,b)}
function Uwb(a,b){if(a.s!=b){return false}try{gi(b,null)}finally{z3(a.Ug(),b.$c());a.s=null}return true}
function Vwb(a,b){if(b==a.s){return}!!b&&(Vab(b.Bc,57)&&Tab(b.Bc,57).wf(b),ei(b));!!a.s&&Uwb(a,a.s);a.s=b;if(b){irb(O3(a.Cc),Hi(a.s));gi(b,a)}}
function xxb(a,b){var c,d,e,g,i,j;a.j||(b=1-b);i=0;e=0;g=0;c=0;d=Zab(b*a.e);j=Zab(b*a.f);switch(0){case 2:case 0:i=a.e-d>>1;e=a.f-j>>1;g=e+j;c=i+d;}Syb(a.b.Cc,'rect('+i+iTb+g+iTb+c+iTb+e+'px)')}
function fxb(){Wwb.call(this,$doc.createElement(DNb));this.e=new lxb;this.p=new zxb(this);w3(this.Cc,$doc.createElement(DNb));cxb(this,0,0);P3(O3(this.Cc))[eOb]='gwt-PopupPanel';O3(this.Cc)[eOb]='popupContent'}
function ge(a){var b,c;!a.c&&(a.c=(b=new Db((!a.C&&(a.C=new W6),a.C),(!a.d&&(a.d=new Ub(new Og)),a.d),(!a.b&&(a.b=new Nb),c=new wg((!a.C&&(a.C=new W6),a.C),Od(!a.C&&(a.C=new W6))),_d(c,(!a.F&&(a.F=new pAb),a.F)),c)),Ud(b,(!a.F&&(a.F=new pAb),a.F)),b));return a.c}
function zg(){var a,b,c,d;this.c=new fxb;new hJb;this.c.k=true;this.c.c=true;this.c.b=true;this.c.g=true;this.b=new QU;hk(this.b,800,-1);NU(this.b,(eV(),dV));aH(this.b,(gn(),dn));d=new EG(new GX);a=Tab(d.mb,87);a.b=true;d.Nb=1;d.kc&&fs(Qs(Hi(d),kRb),true);c=new DG;b=new fY;eY(b,dV);WF(c,b);Twb(this.c,this.b)}
function Ub(){var a,b,c,d,e,g;this.c=new EG(new $W);aj(this.c,true);hj(this.c,fbb.e);d=new dH;d.Ff('Projects');a=new BX((An(),zn));a.b=true;a.g=true;g=new fQ;g.Nb=1;g.kc&&fs(Qs(Hi(g),kRb),true);g.tb=true;g.sb=true;b=new EP('Add',Zvb((Pg(),Ng(),Dg)));pP(b,new ac(this));bQ(g,b,g.lb.c);e=new x0;e.Nb=1;e.kc&&fs(Qs(Hi(e),kRb),true);bQ(g,e,g.lb.c);c=new EP(ySb,Zvb((Rg(),Fg)));bQ(g,c,g.lb.c);xG(d,g,d.lb.c);this.b=new DG;WF(this.b,new UX);aj(this.b,true);vG(this.c,d,a);WF(d,new OX(0));qG(d,(Kn(),Gn));vG(this.c,this.b,new BX(vn))}
var kTb='co.edu.unal.scrum.client.projects.',iTb='px, ';tpb(5,6,{10:1,117:1,156:1},Db);_.Ec=function Eb(){};_.Gc=function Fb(){};_.Hc=function Gb(){};_.Ic=function Hb(){nb(this,new OCb((Kc(),Ec),this))};_.b=null;tpb(11,12,{2:1},Ub);_.Mc=function Vb(){return this.c};_.Kc=function Wb(a,b){if(a===(Bb(),zb)){if(b){VF(this.b);uG(this.b,b)}}};_.b=null;_.c=null;tpb(14,15,eMb,ac);_.Nc=function bc(a){_b(this,Tab(a,30))};_.b=null;tpb(45,1,iMb);_.Yc=function Ve(){yBb(this.c,ge(this.b.b))};tpb(65,7,bMb,wg);_.Ec=function xg(){};tpb(66,28,hMb,zg);_.Mc=function Ag(){return this.c};_.b=null;_.c=null;tpb(384,375,{86:1,89:1},EX);tpb(385,280,{87:1},GX);_.Nf=function HX(a,b){var c,d,e,g,i,j,k;if(!this.c){ui(a,'x-column-layout-ct');this.c=_q(b,kv("<div class='x-column-inner'><\/div>"));_q(this.c,kv("<div class='x-clear'><\/div>"))}aK(this,a,this.c);j=Cr(b,true);k=j.c-(this.b?(jv(),hv==-1&&(hv=pv()),jv(),hv):0);i=k;d=a.lb.c;for(g=0;g<d;++g){c=g<a.lb.c?Tab(_Ib(a.lb,g),55):null;e=Tab(Gi(c,hTb),89);!!e&&Vab(e,86)?Tab(e,86):new EX;i-=UJ(c)}for(g=0;g<d;++g){c=g<a.lb.c?Tab(_Ib(a.lb,g),55):null;e=Tab(Gi(c,hTb),89);!!e&&Vab(e,86)?Tab(e,86):new EX;Vab(c,53)?hk(Tab(c,53),-1,-1):c.kc&&ss(TJ(c.$c()),-1,-1,true)}};_.b=false;_.c=null;tpb(678,664,fNb);_.Ug=function Xwb(){return this.Cc};_.ze=function Ywb(){return new jyb(this)};_.Rg=function Zwb(a){return Uwb(this,a)};_.s=null;tpb(677,678,{113:1,117:1,134:1,141:1,142:1,143:1,144:1,145:1,148:1,149:1},fxb);_.Ug=function gxb(){return O3(this.Cc)};_._c=function hxb(){return !NFb($Nb,this.Cc.style[ZNb])};_.hd=function ixb(){this.q&&yxb(this.p,false,true)};_.b=false;_.c=false;_.d=null;_.f=null;_.g=false;_.i=false;_.j=-1;_.k=false;_.n=null;_.o=false;_.q=false;_.r=-1;tpb(679,1,KMb,lxb);_.If=function mxb(a){kxb()};tpb(682,211,{},zxb);_.Qe=function Axb(){vxb(this)};_.Re=function Bxb(){this.e=D3(this.b.Cc,jTb);this.f=D3(this.b.Cc,VRb);this.b.Cc.style[GSb]=$Nb;xxb(this,(1+Math.cos(3.141592653589793))/2)};_.Se=function Cxb(a){xxb(this,a)};_.b=null;_.c=false;_.d=false;_.e=0;_.f=-1;_.g=null;_.i=null;_.j=false;tpb(691,1,{},jyb);_.De=function kyb(){return this.b};_.Ee=function lyb(){return iyb(this)};_.Fe=function myb(){!!this.c&&Uwb(this.d,this.c)};_.c=null;_.d=null;var dbb=MDb(vQb,'HomePresenter',5),ebb=MDb(vQb,'HomeView$1',14),Ybb=MDb(kTb,'TeamEditorPresenter',65),Zbb=MDb(kTb,'TeamEditorView',66),dhb=MDb(lTb,'ColumnLayout',385),jlb=MDb(ZQb,'SimplePanel',678),blb=MDb(ZQb,'PopupPanel',677),alb=MDb(ZQb,'PopupPanel$ResizeAnimation',682),Ykb=MDb(ZQb,'PopupPanel$1',679),ilb=MDb(ZQb,'SimplePanel$1',691),chb=MDb(lTb,'ColumnData',384);sNb(S1)(5);