function JX(){}
function Qyb(){}
function SU(a,b){a.f=b}
function Vd(a,b){a.Cc(b)}
function ae(a,b){a.Cc(b)}
function bc(a){this.a=a}
function zyb(a){this.Bc=a}
function Db(a){lb(a,a.a)}
function Pd(){return new Ag}
function xg(a,b){vb.call(this,a,b)}
function czb(a){MA.call(this);this.a=a}
function Ozb(a){this.c=a;this.a=!!this.c.r}
function LX(){kK.call(this);this.t=I9b;this.u=true}
function ac(a){!!a.a.k&&Db(wbb(a.a.k,10))}
function wyb(a,b){if(a.r){throw new oGb(N9b)}yyb(a,b)}
function Nzb(a){if(!a.a||!a.c.r){throw new rNb}a.a=false;return a.b=a.c.r}
function Eb(a,b,c){Cb();vb.call(this,a,b);this.a=c;wbb(this.g,2).Kc(this)}
function xyb(a,b){if(a.r!=b){return false}try{ji(b,null)}finally{E3(a._g(),b.Zc());a.r=null}return true}
function yyb(a,b){if(b==a.r){return}!!b&&(ybb(b.Ac,57)&&wbb(b.Ac,57).wf(b),hi(b));!!a.r&&xyb(a,a.r);a.r=b;if(b){ysb(T3(a.Bc),Ki(a.r));ji(b,a)}}
function Kyb(){zyb.call(this,W3($doc,zPb));this.d=new Qyb;this.o=new czb(this);B3(this.Bc,W3($doc,zPb));Hyb(this,0,0);U3(T3(this.Bc))[PQb]=O9b;T3(this.Bc)[PQb]=P9b}
function azb(a,b){var c,d,e,g,i,j;a.i||(b=1-b);i=0;e=0;g=0;c=0;d=Cbb(b*a.d);j=Cbb(b*a.e);switch(0){case 2:case 0:i=a.d-d>>1;e=a.e-j>>1;g=e+j;c=i+d;}EAb(a.a.Bc,Q9b+i+R9b+g+R9b+c+R9b+e+S9b)}
function he(a){var b,c;!a.b&&(a.b=(b=new Eb((!a.B&&(a.B=new y7),a.B),(!a.c&&(a.c=new Vb(new Rg)),a.c),(!a.a&&(a.a=new Ob),c=new xg((!a.B&&(a.B=new y7),a.B),Pd(!a.B&&(a.B=new y7))),ae(c,(!a.E&&(a.E=new eCb),a.E)),c)),Vd(b,(!a.E&&(a.E=new eCb),a.E)),b));return a.b}
function Ag(){var a,b,c,d;this.b=new Kyb;new ZKb;this.b.j=true;this.b.b=true;this.b.a=true;this.b.f=true;this.a=new VU;kk(this.a,800,-1);SU(this.a,(jV(),iV));fH(this.a,(ln(),hn));d=new JG(new LX);a=wbb(d.lb,87);a.a=true;d.Mb=1;d.jc&&js(Us(Ki(d),P2b),true);c=new IG;b=new kY;jY(b,iV);_F(c,b);wyb(this.b,this.a)}
function Vb(){var a,b,c,d,e,g;this.b=new JG(new dX);dj(this.b,true);kj(this.b,Kbb.d);d=new iH;d.Ff(G9b);a=new GX((En(),Dn));a.a=true;a.f=true;g=new kQ;g.Mb=1;g.jc&&js(Us(Ki(g),P2b),true);g.sb=true;g.rb=true;b=new JP(H9b,Cxb((Sg(),Qg(),Gg)));uP(b,new bc(this));gQ(g,b,g.kb.b);e=new C0;e.Mb=1;e.jc&&js(Us(Ki(e),P2b),true);gQ(g,e,g.kb.b);c=new JP(Z6b,Cxb((Ug(),Ig)));gQ(g,c,g.kb.b);CG(d,g,d.kb.b);this.a=new IG;_F(this.a,new ZX);dj(this.a,true);AG(this.b,d,a);_F(d,new TX(0));vG(d,(On(),Kn));AG(this.b,this.a,new GX(zn))}
var L9b="<div class='x-clear'><\/div>",K9b="<div class='x-column-inner'><\/div>",H9b='Add',eac='ColumnData',$9b='ColumnLayout',U9b='HomePresenter',V9b='HomeView$1',aac='PopupPanel',cac='PopupPanel$1',bac='PopupPanel$ResizeAnimation',G9b='Projects',_9b='SimplePanel',N9b='SimplePanel can only contain one child widget',dac='SimplePanel$1',X9b='TeamEditorPresenter',Y9b='TeamEditorView',W9b='co.edu.unal.scrum.client.projects.',O9b='gwt-PopupPanel',P9b='popupContent',S9b='px)',R9b='px, ',Q9b='rect(',J9b='x-column-layout-ct';gqb(5,6,{10:1,117:1,157:1},Eb);_.Dc=function Fb(){};_.Fc=function Gb(){};_.Gc=function Hb(){};_.Hc=function Ib(){ob(this,new DEb((Lc(),Fc),this))};_.a=null;gqb(11,12,{2:1},Vb);_.Lc=function Wb(){return this.b};_.Jc=function Xb(a,b){if(a===(Cb(),Ab)){if(b){$F(this.a);zG(this.a,b)}}};_.a=null;_.b=null;gqb(14,15,WNb,bc);_.Mc=function cc(a){ac(this,wbb(a,30))};_.a=null;gqb(45,1,$Nb);_.Xc=function We(){nDb(this.b,he(this.a.a))};gqb(65,7,TNb,xg);_.Dc=function yg(){};gqb(66,28,ZNb,Ag);_.Lc=function Bg(){return this.b};_.a=null;_.b=null;gqb(385,376,{86:1,89:1},JX);gqb(386,281,{87:1},LX);_.Nf=function MX(a,b){var c,d,e,g,i,j,k;if(!this.b){xi(a,J9b);this.b=dr(b,ov(K9b));dr(this.b,ov(L9b))}fK(this,a,this.b);j=Gr(b,true);k=j.b-(this.a?(nv(),lv==-1&&(lv=tv()),nv(),lv):0);i=k;d=a.kb.b;for(g=0;g<d;++g){c=g<a.kb.b?wbb(RKb(a.kb,g),55):null;e=wbb(Ji(c,M9b),89);!!e&&ybb(e,86)?wbb(e,86):new JX;i-=ZJ(c)}for(g=0;g<d;++g){c=g<a.kb.b?wbb(RKb(a.kb,g),55):null;e=wbb(Ji(c,M9b),89);!!e&&ybb(e,86)?wbb(e,86):new JX;ybb(c,53)?kk(wbb(c,53),-1,-1):c.jc&&ws(YJ(c.Zc()),-1,-1,true)}};_.a=false;_.b=null;gqb(688,674,XOb);_._g=function Ayb(){return this.Bc};_.ze=function Byb(){return new Ozb(this)};_.Yg=function Cyb(a){return xyb(this,a)};_.r=null;gqb(687,688,{113:1,117:1,135:1,142:1,143:1,144:1,145:1,146:1,149:1,150:1},Kyb);_._g=function Lyb(){return T3(this.Bc)};_.$c=function Myb(){return !DHb(JQb,this.Bc.style[IQb])};_.gd=function Nyb(){this.p&&bzb(this.o,false,true)};_.a=false;_.b=false;_.c=null;_.e=null;_.f=false;_.g=false;_.i=-1;_.j=false;_.k=null;_.n=false;_.p=false;_.q=-1;gqb(689,1,AOb,Qyb);_.If=function Ryb(a){Pyb()};gqb(692,212,{},czb);_.Qe=function dzb(){$yb(this)};_.Re=function ezb(){this.d=I3(this.a.Bc,T9b);this.e=I3(this.a.Bc,l4b);this.a.Bc.style[D7b]=JQb;azb(this,(1+Math.cos(3.141592653589793))/2)};_.Se=function fzb(a){azb(this,a)};_.a=null;_.b=false;_.c=false;_.d=0;_.e=-1;_.f=null;_.g=null;_.i=false;gqb(701,1,{},Ozb);_.De=function Pzb(){return this.a};_.Ee=function Qzb(){return Nzb(this)};_.Fe=function Rzb(){!!this.b&&xyb(this.c,this.b)};_.b=null;_.c=null;var Ibb=BFb(DYb,U9b,5),Jbb=BFb(DYb,V9b,14),Bcb=BFb(W9b,X9b,65),Ccb=BFb(W9b,Y9b,66),Jhb=BFb(Z9b,$9b,386),Vlb=BFb(o1b,_9b,688),Nlb=BFb(o1b,aac,687),Mlb=BFb(o1b,bac,692),Ilb=BFb(o1b,cac,689),Ulb=BFb(o1b,dac,701),Ihb=BFb(Z9b,eac,385);iPb(X1)(5);